package reality_test

// Precision ratchet.
//
// The files testdata/stress/precision_*.json (generated by the scripts in
// tools/stressgolden from mpmath at 60 digits) pair functions with the
// precision their own docstrings claim, at inputs where that claim is hardest
// to keep: distribution tails, large shapes, ties. Every case must meet its
// claim, except the measured violations listed in knownPrecisionViolations.
// That list is a ratchet:
//   - a listed case that now meets its claim fails the test, so the entry is
//     removed in the change that fixes it;
//   - an unlisted case that misses its claim fails the test.
// The list can therefore only shrink.
//
// Report every case with its error:
//
//	REALITY_PRECISION_REPORT=1 go test -run TestPrecisionClaims -v .
//
// To cover another area, add its own case file, testdata/stress/
// precision_<area>.json, and a test file that registers the area's evaluators
// with registerPrecisionEvaluator and its measured violations with
// registerKnownPrecisionViolations, both from init. Case ids must be unique
// across files.

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/davly/reality/combinatorics"
	"github.com/davly/reality/prob"
)

// knownPrecisionViolations maps a case id to its measured state when it was
// listed. Remove an entry in the same change that fixes it.
var knownPrecisionViolations = map[string]string{}

type precisionCase struct {
	ID      string         `json:"id"`
	Func    string         `json:"func"`
	Args    map[string]any `json:"args"`
	Want    float64        `json:"want"`
	Tol     float64        `json:"tol"`
	TolKind string         `json:"tol_kind"`
	Claim   string         `json:"claim"`
}

func argF(c precisionCase, k string) float64 {
	v, ok := c.Args[k].(float64)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not a number", c.ID, k))
	}
	return v
}

func argI(c precisionCase, k string) int {
	v := argF(c, k)
	if v != math.Trunc(v) {
		panic(fmt.Sprintf("%s: argument %q is not an integer", c.ID, k))
	}
	return int(v)
}

// precisionEvaluators maps a case's "func" to the code that evaluates it.
var precisionEvaluators = map[string]func(precisionCase) (float64, error){}

// registerPrecisionEvaluator adds the evaluator for one function. Call it from
// init; a duplicate name panics.
func registerPrecisionEvaluator(name string, f func(precisionCase) (float64, error)) {
	if _, dup := precisionEvaluators[name]; dup {
		panic("duplicate precision evaluator for " + name)
	}
	precisionEvaluators[name] = f
}

// registerKnownPrecisionViolations adds an area's measured violations to
// knownPrecisionViolations. Call it from init; a duplicate id panics.
// buildDependentPrefix marks a listed violation whose outcome differs between
// supported builds: it meets its claim on some targets and misses on others,
// because fused multiply-adds (GOAMD64=v3, arm64) round intermediates
// differently from the default amd64 build. A single test run cannot tell
// whether such a case has started meeting its claim everywhere, so for a
// listed case whose reason starts with this prefix both outcomes are accepted
// and the outcome is always logged, never silent. The reason must name the
// builds measured on each side. The way out of this state is to make the
// function build-independent, then drop the prefix so the ratchet bites again.
const buildDependentPrefix = "build-dependent:"

// precisionOutcome is the ratchet's verdict for one case, kept pure so both
// polarities of every state can be tested without a second build target.
// It returns "" when the case needs no action, otherwise the defect:
// "meets-listed" (remove the listing), "violates-unlisted" (list it or fix
// the code) or "build-dependent" (accepted, but reported).
func precisionOutcome(meets, listed bool, why string) string {
	switch {
	case listed && strings.HasPrefix(why, buildDependentPrefix):
		return "build-dependent"
	case meets && listed:
		return "meets-listed"
	case !meets && !listed:
		return "violates-unlisted"
	}
	return ""
}

func registerKnownPrecisionViolations(m map[string]string) {
	for id, why := range m {
		if _, dup := knownPrecisionViolations[id]; dup {
			panic("duplicate known precision violation " + id)
		}
		knownPrecisionViolations[id] = why
	}
}

func evalPrecisionCase(c precisionCase) (float64, error) {
	f, ok := precisionEvaluators[c.Func]
	if !ok {
		return 0, fmt.Errorf("no evaluator for %s", c.Func)
	}
	return f(c)
}

func init() {
	registerPrecisionEvaluator("TTestOneSample", func(c precisionCase) (float64, error) {
		raw, ok := c.Args["data"].([]any)
		if !ok {
			return 0, fmt.Errorf("data is not an array")
		}
		data := make([]float64, len(raw))
		for i, v := range raw {
			data[i] = v.(float64)
		}
		_, p := prob.TTestOneSample(data, argF(c, "mu0"))
		return p, nil
	})
	registerPrecisionEvaluator("ChiSquaredTest", func(c precisionCase) (float64, error) {
		k, e, d := argI(c, "k"), argF(c, "e"), argF(c, "d")
		obs, exp := make([]float64, k), make([]float64, k)
		for i := range obs {
			exp[i] = e
			if i%2 == 0 {
				obs[i] = e + d
			} else {
				obs[i] = e - d
			}
		}
		_, p := prob.ChiSquaredTest(obs, exp)
		return p, nil
	})
	registerPrecisionEvaluator("PoissonCDF", func(c precisionCase) (float64, error) {
		return prob.PoissonCDF(argI(c, "k"), argF(c, "lambda")), nil
	})
	registerPrecisionEvaluator("GammaCDF", func(c precisionCase) (float64, error) {
		return prob.GammaCDF(argF(c, "x"), argF(c, "k"), argF(c, "theta")), nil
	})
	registerPrecisionEvaluator("NormalQuantile", func(c precisionCase) (float64, error) {
		return prob.NormalQuantile(argF(c, "p"), 0, 1), nil
	})
	registerPrecisionEvaluator("ExponentialQuantile", func(c precisionCase) (float64, error) {
		return prob.ExponentialQuantile(argF(c, "p"), argF(c, "lambda")), nil
	})
	registerPrecisionEvaluator("ProportionBayesFactor10", func(c precisionCase) (float64, error) {
		bf, _ := prob.ProportionBayesFactor10(argI(c, "k"), argI(c, "n"))
		return bf, nil
	})
	registerPrecisionEvaluator("BinomialCoeff", func(c precisionCase) (float64, error) {
		return combinatorics.BinomialCoeff(argI(c, "n"), argI(c, "k")), nil
	})
	registerPrecisionEvaluator("Factorial", func(c precisionCase) (float64, error) {
		return combinatorics.Factorial(argI(c, "n")), nil
	})
	registerPrecisionEvaluator("FisherExactTest", func(c precisionCase) (float64, error) {
		return prob.FisherExactTest(argI(c, "a"), argI(c, "b"), argI(c, "c"), argI(c, "d")), nil
	})
	registerPrecisionEvaluator("BetaCDF", func(c precisionCase) (float64, error) {
		return prob.BetaCDF(argF(c, "x"), argF(c, "alpha"), argF(c, "beta")), nil
	})
}

// precisionError returns the error measure the case's claim is stated in.
func precisionError(c precisionCase, got float64) float64 {
	if math.IsNaN(got) || math.IsInf(got, 0) {
		return math.Inf(1)
	}
	diff := math.Abs(got - c.Want)
	if c.TolKind == "abs" || c.Want == 0 {
		return diff
	}
	return diff / math.Abs(c.Want)
}

func TestPrecisionClaims(t *testing.T) {
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	files, err := filepath.Glob(filepath.Join(root, "testdata", "stress", "precision_*.json"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no testdata/stress/precision_*.json case files")
	}
	sort.Strings(files)
	var cases []precisionCase
	for _, path := range files {
		data, err := os.ReadFile(path) // #nosec G304 -- case files inside this module
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var doc struct {
			Cases []precisionCase `json:"cases"`
		}
		if err := json.Unmarshal(data, &doc); err != nil {
			t.Fatalf("parsing %s: %v", path, err)
		}
		if len(doc.Cases) == 0 {
			t.Fatalf("%s has no cases: the generator output is empty", path)
		}
		cases = append(cases, doc.Cases...)
	}

	report := os.Getenv("REALITY_PRECISION_REPORT") != ""
	outcomes := newOutcomeWriter(t)
	defer outcomes.close(t)
	seen := map[string]bool{}
	for _, c := range cases {
		if seen[c.ID] {
			t.Fatalf("duplicate case id %s", c.ID)
		}
		seen[c.ID] = true
		if c.TolKind != "rel" && c.TolKind != "abs" {
			t.Fatalf("%s: unknown tol_kind %q", c.ID, c.TolKind)
		}
		got, err := evalPrecisionCase(c)
		if err != nil {
			t.Errorf("%s: %v", c.ID, err)
			continue
		}
		e := precisionError(c, got)
		meets := e <= c.Tol
		why, listed := knownPrecisionViolations[c.ID]
		if report {
			status := "meets claim"
			if !meets {
				status = "VIOLATES claim"
			}
			t.Logf("%-30s %-15s got %-24.17g want %-24.17g %s err %.3g (tol %.3g)", c.ID, status, got, c.Want, c.TolKind, e, c.Tol)
		}
		outcomes.record(t, c.ID, meets, listed, strings.HasPrefix(why, buildDependentPrefix))
		switch precisionOutcome(meets, listed, why) {
		case "build-dependent":
			outcome := "violates"
			if meets {
				outcome = "meets"
			}
			t.Logf("%s is build-dependent and %s its claim on this build (%s err %.3g, tol %.3g): %s", c.ID, outcome, c.TolKind, e, c.Tol, why)
		case "meets-listed":
			t.Errorf("%s now meets its claim (%s err %.3g <= %.3g): remove it from knownPrecisionViolations", c.ID, c.TolKind, e, c.Tol)
		case "violates-unlisted":
			t.Errorf("%s violates its documented precision: got %.17g, want %.17g (%s err %.3g > %.3g)\n  claim: %s", c.ID, got, c.Want, c.TolKind, e, c.Tol, c.Claim)
		}
	}
	var stale []string
	for id := range knownPrecisionViolations {
		if !seen[id] {
			stale = append(stale, id)
		}
	}
	sort.Strings(stale)
	if len(stale) > 0 {
		t.Errorf("knownPrecisionViolations lists cases that no longer exist: %v", stale)
	}
}

// TestPrecisionRegistryRejectsDuplicates checks that two area files cannot
// silently shadow each other's evaluators or listed violations.
func TestPrecisionRegistryRejectsDuplicates(t *testing.T) {
	mustPanic := func(what string, f func()) {
		t.Helper()
		defer func() {
			if recover() == nil {
				t.Errorf("a duplicate %s was accepted", what)
			}
		}()
		f()
	}
	mustPanic("evaluator", func() {
		registerPrecisionEvaluator("GammaCDF", func(precisionCase) (float64, error) { return 0, nil })
	})
	const id = "test/registry-duplicate"
	registerKnownPrecisionViolations(map[string]string{id: "registered by this test"})
	defer delete(knownPrecisionViolations, id)
	mustPanic("listed violation", func() {
		registerKnownPrecisionViolations(map[string]string{id: "registered twice"})
	})
}

// TestPrecisionOutcomePolarity proves each ratchet state in both directions,
// including that the build-dependent marker accepts either outcome and that a
// plain reason still demands the listing be removed once the case meets.
func TestPrecisionOutcomePolarity(t *testing.T) {
	cases := []struct {
		name          string
		meets, listed bool
		why, want     string
	}{
		{"unlisted and meets", true, false, "", ""},
		{"listed and violates", false, true, "measured 3e-9 against 1e-12", ""},
		{"listed and meets", true, true, "measured 3e-9 against 1e-12", "meets-listed"},
		{"unlisted and violates", false, false, "", "violates-unlisted"},
		{"build-dependent and meets", true, true, buildDependentPrefix + " meets on amd64, violates on arm64", "build-dependent"},
		{"build-dependent and violates", false, true, buildDependentPrefix + " meets on amd64, violates on arm64", "build-dependent"},
		{"prefix without a listing is ignored", false, false, buildDependentPrefix + " not registered", "violates-unlisted"},
	}
	for _, c := range cases {
		if got := precisionOutcome(c.meets, c.listed, c.why); got != c.want {
			t.Errorf("%s: got %q, want %q", c.name, got, c.want)
		}
	}
}

// precisionOutcomeRecord is one case's outcome on one build target. CI writes
// one file per target (REALITY_PRECISION_OUTCOMES names the file,
// REALITY_BUILD_TARGET labels the build) and a final job joins them with
// TestPrecisionBuildDependentJoin. Without the join, a build-dependent listing
// could only grow: nothing would notice a case that has started meeting its
// claim on every build, or one that violates everywhere and belongs in the
// plain list.
type precisionOutcomeRecord struct {
	ID             string `json:"id"`
	Target         string `json:"target"`
	Meets          bool   `json:"meets"`
	Listed         bool   `json:"listed"`
	BuildDependent bool   `json:"build_dependent"`
}

type outcomeWriter struct {
	f      *os.File
	target string
}

func newOutcomeWriter(t *testing.T) *outcomeWriter {
	t.Helper()
	path := os.Getenv("REALITY_PRECISION_OUTCOMES")
	if path == "" {
		return &outcomeWriter{}
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("REALITY_PRECISION_OUTCOMES: %v", err)
	}
	target := os.Getenv("REALITY_BUILD_TARGET")
	if target == "" {
		target = runtime.GOOS + "/" + runtime.GOARCH
	}
	return &outcomeWriter{f: f, target: target}
}

func (w *outcomeWriter) record(t *testing.T, id string, meets, listed, buildDependent bool) {
	if w.f == nil {
		return
	}
	b, err := json.Marshal(precisionOutcomeRecord{ID: id, Target: w.target, Meets: meets, Listed: listed, BuildDependent: buildDependent})
	if err != nil {
		t.Fatalf("outcome record: %v", err)
	}
	if _, err := w.f.Write(append(b, '\n')); err != nil {
		t.Fatalf("outcome record: %v", err)
	}
}

func (w *outcomeWriter) close(t *testing.T) {
	if w.f != nil {
		if err := w.f.Close(); err != nil {
			t.Errorf("outcome file: %v", err)
		}
	}
}

// joinPrecisionOutcomes is the pure core of the cross-build join. For every
// case it returns a defect line, or nothing when the records are consistent:
//   - a build-dependent case must meet its claim on at least one target AND
//     violate it on at least one other (otherwise the prefix no longer tells
//     the truth: drop it, and list or unlist the case);
//   - every other case must have the same outcome on every target (otherwise
//     it is build-dependent and must say so);
//   - fewer than two targets is not a join; that is reported, never passed.
func joinPrecisionOutcomes(records []precisionOutcomeRecord) []string {
	targets := map[string]bool{}
	type agg struct {
		meets, violates []string
		buildDependent  bool
	}
	byID := map[string]*agg{}
	for _, r := range records {
		targets[r.Target] = true
		a := byID[r.ID]
		if a == nil {
			a = &agg{}
			byID[r.ID] = a
		}
		if r.Meets {
			a.meets = append(a.meets, r.Target)
		} else {
			a.violates = append(a.violates, r.Target)
		}
		a.buildDependent = a.buildDependent || r.BuildDependent
	}
	if len(targets) < 2 {
		return []string{fmt.Sprintf("the join needs outcomes from at least two build targets, got %d", len(targets))}
	}
	ids := make([]string, 0, len(byID))
	for id := range byID {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var defects []string
	for _, id := range ids {
		a := byID[id]
		sort.Strings(a.meets)
		sort.Strings(a.violates)
		switch {
		case a.buildDependent && len(a.meets) == 0:
			defects = append(defects, fmt.Sprintf("%s is listed build-dependent but violates its claim on every target %v: list it plainly", id, a.violates))
		case a.buildDependent && len(a.violates) == 0:
			defects = append(defects, fmt.Sprintf("%s is listed build-dependent but meets its claim on every target %v: drop the listing", id, a.meets))
		case !a.buildDependent && len(a.meets) > 0 && len(a.violates) > 0:
			defects = append(defects, fmt.Sprintf("%s differs between builds (meets on %v, violates on %v): list it as build-dependent", id, a.meets, a.violates))
		}
	}
	return defects
}

// TestPrecisionBuildDependentJoin runs only in the CI join job, where
// REALITY_PRECISION_JOIN_DIR holds one outcome file per build target. It is
// the part of the ratchet a single build cannot run.
func TestPrecisionBuildDependentJoin(t *testing.T) {
	dir := os.Getenv("REALITY_PRECISION_JOIN_DIR")
	if dir == "" {
		t.Skip("REALITY_PRECISION_JOIN_DIR not set: the cross-build join runs in CI")
	}
	var records []precisionOutcomeRecord
	var files int
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".jsonl") {
			return nil
		}
		files++
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, line := range strings.Split(string(b), "\n") {
			if strings.TrimSpace(line) == "" {
				continue
			}
			var r precisionOutcomeRecord
			if err := json.Unmarshal([]byte(line), &r); err != nil {
				return fmt.Errorf("%s: %v", path, err)
			}
			records = append(records, r)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("reading outcome files: %v", err)
	}
	if files == 0 {
		t.Fatalf("no outcome files under %s: the join could not look", dir)
	}
	for _, d := range joinPrecisionOutcomes(records) {
		t.Error(d)
	}
	t.Logf("joined %d records from %d files", len(records), files)
}

// TestPrecisionJoinPolarity proves the join in both directions without CI.
func TestPrecisionJoinPolarity(t *testing.T) {
	rec := func(id, target string, meets, bd bool) precisionOutcomeRecord {
		return precisionOutcomeRecord{ID: id, Target: target, Meets: meets, Listed: !meets || bd, BuildDependent: bd}
	}
	cases := []struct {
		name    string
		records []precisionOutcomeRecord
		defects int
	}{
		{"consistent: plain case meets everywhere", []precisionOutcomeRecord{rec("a", "x", true, false), rec("a", "y", true, false)}, 0},
		{"consistent: plain listed case violates everywhere", []precisionOutcomeRecord{rec("a", "x", false, false), rec("a", "y", false, false)}, 0},
		{"consistent: build-dependent case differs", []precisionOutcomeRecord{rec("a", "x", true, true), rec("a", "y", false, true)}, 0},
		{"defect: build-dependent case meets everywhere", []precisionOutcomeRecord{rec("a", "x", true, true), rec("a", "y", true, true)}, 1},
		{"defect: build-dependent case violates everywhere", []precisionOutcomeRecord{rec("a", "x", false, true), rec("a", "y", false, true)}, 1},
		{"defect: plain case differs between builds", []precisionOutcomeRecord{rec("a", "x", true, false), rec("a", "y", false, false)}, 1},
		{"defect: one target is not a join", []precisionOutcomeRecord{rec("a", "x", true, true)}, 1},
	}
	for _, c := range cases {
		if got := len(joinPrecisionOutcomes(c.records)); got != c.defects {
			t.Errorf("%s: %d defect(s), want %d: %v", c.name, got, c.defects, joinPrecisionOutcomes(c.records))
		}
	}
}
