package reality_test

// Precision claims of the numerical packages: linalg, optim and its
// subpackages, calculus and chaos. The cases live in
// testdata/stress/precision_numerics.json, generated by
// tools/stressgolden/numerics.py (mpmath at 60 digits); each case states how
// it reads the doc comment it checks. The ratchet itself is
// TestPrecisionClaims in precision_test.go.
//
// For a vector or matrix result an evaluator returns one error measure, named
// in the case's claim, and the case expects 0. A function that reports failure
// where its doc comment promises a result is scored as NaN (a miss), and a
// promised failure (nil, false) that does not happen scores 1 against 0.

import (
	"fmt"
	"math"
	"math/big"

	"github.com/davly/reality/linalg"
)

func numVec(c precisionCase, k string) []float64 {
	raw, ok := c.Args[k].([]any)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not an array", c.ID, k))
	}
	v := make([]float64, len(raw))
	for i, x := range raw {
		f, ok := x.(float64)
		if !ok {
			panic(fmt.Sprintf("%s: argument %q[%d] is not a number", c.ID, k, i))
		}
		v[i] = f
	}
	return v
}

func numStr(c precisionCase, k string) string {
	s, ok := c.Args[k].(string)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not a string", c.ID, k))
	}
	return s
}

// numNormwiseErr returns max_i |got_i - want_i| / max_i |want_i|.
func numNormwiseErr(got, want []float64) float64 {
	if len(got) != len(want) {
		return math.Inf(1)
	}
	var e, m float64
	for i := range want {
		d := math.Abs(got[i] - want[i])
		if math.IsNaN(d) {
			return math.Inf(1)
		}
		e = math.Max(e, d)
		m = math.Max(m, math.Abs(want[i]))
	}
	if m == 0 {
		return e
	}
	return e / m
}

// numMaxAbsErr returns max_i |got_i - want_i|.
func numMaxAbsErr(got, want []float64) float64 {
	if len(got) != len(want) {
		return math.Inf(1)
	}
	var e float64
	for i := range want {
		d := math.Abs(got[i] - want[i])
		if math.IsNaN(d) {
			return math.Inf(1)
		}
		e = math.Max(e, d)
	}
	return e
}

// numExactNorm2 returns the 2-norm of v, accumulated exactly in big.Float and
// rounded once at the end, so the measure adds no error of its own beyond
// that final rounding.
func numExactNorm2(v []float64) float64 {
	const prec = 4096
	sum := new(big.Float).SetPrec(prec)
	for _, x := range v {
		if math.IsNaN(x) || math.IsInf(x, 0) {
			return math.NaN()
		}
		t := new(big.Float).SetPrec(prec).SetFloat64(x)
		sum.Add(sum, t.Mul(t, t))
	}
	f, _ := new(big.Float).SetPrec(prec).Sqrt(sum).Float64()
	return f
}

func numBool(b bool) float64 {
	if b {
		return 1
	}
	return 0
}

func init() {
	registerLinalgEvaluators()
	registerKnownPrecisionViolations(numericsKnownViolations)
}

// numericsKnownViolations lists the measured misses, each with its error on
// the default amd64 build (the GOAMD64=v3 build measures the same unless the
// entry says otherwise).
var numericsKnownViolations = map[string]string{
	// linalg
	"numerics/pearson/offset-1e12":               "rel err 3.1e-8: the mean of data at 1e12 rounds, and the centred sums inherit it",
	"numerics/cross/near-parallel":               "normwise rel err 5.0e-8: nearly parallel inputs, the two products of each component cancel",
	"numerics/jamesstein/offset-1e9":             "rel err 3.4e-15 (15 ulps): the grand mean of means at 1e9 rounds",
	"numerics/jamesstein/tiny-scale":             "returns c = 1 for true c = 0.0214: S = 4.7e-302 is under the absolute 1e-300 'identical means' threshold",
	"numerics/lw-identity/offset-1e5-intensity":  "abs err 5.6e-11 > 1e-11: data at 1e5 lose 7 digits in the centring",
	"numerics/lw-constcorr/offset-1e5-intensity": "abs err 5.0e-10 > 1e-11: data at 1e5 lose 7 digits in the centring",
	"numerics/mpbounds/q0.999-min":               "rel err 1.7e-13: lambdaMin = (1 - sqrt q)^2 cancels as q -> 1",
	"numerics/mpbounds/q0.99999-min":             "rel err 2.4e-12: lambdaMin = (1 - sqrt q)^2 cancels as q -> 1",
	"numerics/l2norm/underflow-1e-170":           "returns 0 for (3e-170, 4e-170): the squares underflow",
	"numerics/l2norm/subnormal-squares-1e-160":   "rel err 5.6e-6: the squares of 1e-160 are subnormal",
	"numerics/encdist/underflow-1e-170":          "returns 0 for distinct vectors: the squared differences underflow",
	"numerics/wdist/underflow-1e-170":            "returns 0 for distinct vectors: the squared differences underflow",
	"numerics/l2normalize/underflow-1e-170":      "returns false (zero magnitude) for (3e-170, 4e-170) and leaves it unnormalised",
	"numerics/cosine/underflow-1e-170":           "returns 0 (the zero-magnitude branch) for cosine 0.926: the norms underflow",
	"numerics/cosine/overflow-1e170":             "returns NaN for cosine 0.926: the dot product and norms overflow to Inf",
	"numerics/det/singular-1to9":                 "returns 6.7e-16 for an exactly singular integer matrix: the pivot test is an absolute 1e-300",
	"numerics/det/singular-rank2-covariance":     "returns -5.4e-14 for an exactly singular integer covariance: the pivot test is an absolute 1e-300",
	"numerics/inverse/singular-1to9":             "reports success (inverse entries ~4.5e15) for an exactly singular integer matrix",
	"numerics/inverse/singular-rank2-covariance": "reports success for an exactly singular integer covariance (30 of 49 such rank-2 3x3 matrices pass)",
}

func registerLinalgEvaluators() {
	registerPrecisionEvaluator("linalg.PearsonCorrelation", func(c precisionCase) (float64, error) {
		return linalg.PearsonCorrelation(numVec(c, "x"), numVec(c, "y")), nil
	})
	registerPrecisionEvaluator("linalg.SpearmanCorrelation", func(c precisionCase) (float64, error) {
		return linalg.SpearmanCorrelation(numVec(c, "x"), numVec(c, "y")), nil
	})
	registerPrecisionEvaluator("linalg.Trace", func(c precisionCase) (float64, error) {
		return linalg.Trace(numVec(c, "A"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("linalg.CrossProduct", func(c precisionCase) (float64, error) {
		out := make([]float64, 3)
		linalg.CrossProduct(numVec(c, "a"), numVec(c, "b"), out)
		return numNormwiseErr(out, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("linalg.JamesSteinShrink", func(c precisionCase) (float64, error) {
		_, shrink := linalg.JamesSteinShrink(numVec(c, "means"), argF(c, "variance"))
		return shrink, nil
	})
	lw := func(f func([]float64, int, int) ([]float64, float64)) func(precisionCase) (float64, error) {
		return func(c precisionCase) (float64, error) {
			sigma, intensity := f(numVec(c, "x"), argI(c, "T"), argI(c, "N"))
			switch numStr(c, "measure") {
			case "intensity":
				return intensity, nil
			case "matrix":
				return numNormwiseErr(sigma, numVec(c, "truth")), nil
			}
			return 0, fmt.Errorf("unknown measure %q", numStr(c, "measure"))
		}
	}
	registerPrecisionEvaluator("linalg.LedoitWolfShrinkageIdentity", lw(linalg.LedoitWolfShrinkageIdentity))
	registerPrecisionEvaluator("linalg.LedoitWolfShrinkageConstantCorr", lw(linalg.LedoitWolfShrinkageConstantCorr))
	registerPrecisionEvaluator("linalg.MarchenkoPasturBounds", func(c precisionCase) (float64, error) {
		lo, hi := linalg.MarchenkoPasturBounds(argF(c, "q"))
		if numStr(c, "which") == "min" {
			return lo, nil
		}
		return hi, nil
	})
	registerPrecisionEvaluator("linalg.CleanCorrelation", func(c precisionCase) (float64, error) {
		out := linalg.CleanCorrelation(numVec(c, "corr"), argI(c, "T"), argI(c, "N"))
		return numMaxAbsErr(out, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("linalg.L2Norm", func(c precisionCase) (float64, error) {
		return linalg.L2Norm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.EncodingDistance", func(c precisionCase) (float64, error) {
		return linalg.EncodingDistance(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.DimensionWeightedDistance", func(c precisionCase) (float64, error) {
		return linalg.DimensionWeightedDistance(numVec(c, "a"), numVec(c, "b"), numVec(c, "w")), nil
	})
	registerPrecisionEvaluator("linalg.L2Normalize", func(c precisionCase) (float64, error) {
		v := numVec(c, "v")
		linalg.L2Normalize(v)
		return numExactNorm2(v), nil
	})
	registerPrecisionEvaluator("linalg.CosineSimilarity", func(c precisionCase) (float64, error) {
		return linalg.CosineSimilarity(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.DotProduct", func(c precisionCase) (float64, error) {
		return linalg.DotProduct(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.L1Norm", func(c precisionCase) (float64, error) {
		return linalg.L1Norm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.LInfNorm", func(c precisionCase) (float64, error) {
		return linalg.LInfNorm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.Determinant", func(c precisionCase) (float64, error) {
		return linalg.Determinant(numVec(c, "A"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("linalg.Inverse", func(c precisionCase) (float64, error) {
		n := argI(c, "n")
		out := make([]float64, n*n)
		return numBool(linalg.Inverse(numVec(c, "A"), n, out)), nil
	})
}
