package reality_test

// Precision claims of the numerical packages: linalg, optim and its
// subpackages, calculus and chaos. The cases live in
// testdata/stress/precision_numerics.json, generated by
// tools/stressgolden/numerics.py (mpmath at 60 digits); each case states how
// it reads the doc comment it checks. The ratchet itself is
// TestPrecisionClaims in precision_test.go.
//
// For a vector or matrix result an evaluator returns one error measure, named
// in the case's claim, and the case expects 0. A function that reports failure
// where its doc comment promises a result is scored as NaN (a miss), and a
// promised failure (nil, false) that does not happen scores 1 against 0.

import (
	"errors"
	"fmt"
	"math"
	"math/big"

	"github.com/davly/reality/calculus"
	"github.com/davly/reality/chaos"
	"github.com/davly/reality/linalg"
	"github.com/davly/reality/optim"
	"github.com/davly/reality/optim/hrp"
	"github.com/davly/reality/optim/portfolio"
	"github.com/davly/reality/optim/proximal"
	"github.com/davly/reality/optim/transport"
)

func numVec(c precisionCase, k string) []float64 {
	raw, ok := c.Args[k].([]any)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not an array", c.ID, k))
	}
	v := make([]float64, len(raw))
	for i, x := range raw {
		f, ok := x.(float64)
		if !ok {
			panic(fmt.Sprintf("%s: argument %q[%d] is not a number", c.ID, k, i))
		}
		v[i] = f
	}
	return v
}

func numMat(c precisionCase, k string) [][]float64 {
	raw, ok := c.Args[k].([]any)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not an array", c.ID, k))
	}
	m := make([][]float64, len(raw))
	for i, r := range raw {
		row, ok := r.([]any)
		if !ok {
			panic(fmt.Sprintf("%s: argument %q[%d] is not an array", c.ID, k, i))
		}
		m[i] = make([]float64, len(row))
		for j, x := range row {
			f, ok := x.(float64)
			if !ok {
				panic(fmt.Sprintf("%s: argument %q[%d][%d] is not a number", c.ID, k, i, j))
			}
			m[i][j] = f
		}
	}
	return m
}

func numInts(c precisionCase, k string) []int {
	v := numVec(c, k)
	out := make([]int, len(v))
	for i, x := range v {
		if x != math.Trunc(x) {
			panic(fmt.Sprintf("%s: argument %q[%d] is not an integer", c.ID, k, i))
		}
		out[i] = int(x)
	}
	return out
}

func numStr(c precisionCase, k string) string {
	s, ok := c.Args[k].(string)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not a string", c.ID, k))
	}
	return s
}

// numNormwiseErr returns max_i |got_i - want_i| / max_i |want_i|.
func numNormwiseErr(got, want []float64) float64 {
	if len(got) != len(want) {
		return math.Inf(1)
	}
	var e, m float64
	for i := range want {
		d := math.Abs(got[i] - want[i])
		if math.IsNaN(d) {
			return math.Inf(1)
		}
		e = math.Max(e, d)
		m = math.Max(m, math.Abs(want[i]))
	}
	if m == 0 {
		return e
	}
	return e / m
}

// numMaxAbsErr returns max_i |got_i - want_i|.
func numMaxAbsErr(got, want []float64) float64 {
	if len(got) != len(want) {
		return math.Inf(1)
	}
	var e float64
	for i := range want {
		d := math.Abs(got[i] - want[i])
		if math.IsNaN(d) {
			return math.Inf(1)
		}
		e = math.Max(e, d)
	}
	return e
}

// numExactNorm2 returns the 2-norm of v, accumulated exactly in big.Float and
// rounded once at the end, so the measure adds no error of its own beyond
// that final rounding.
func numExactNorm2(v []float64) float64 {
	const prec = 4096
	sum := new(big.Float).SetPrec(prec)
	for _, x := range v {
		if math.IsNaN(x) || math.IsInf(x, 0) {
			return math.NaN()
		}
		t := new(big.Float).SetPrec(prec).SetFloat64(x)
		sum.Add(sum, t.Mul(t, t))
	}
	f, _ := new(big.Float).SetPrec(prec).Sqrt(sum).Float64()
	return f
}

// numMaxRelErr returns max_i |got_i - want_i| / |want_i| (absolute where
// want_i is 0); a missing result is +Inf.
func numMaxRelErr(got, want []float64) float64 {
	if len(got) != len(want) {
		return math.Inf(1)
	}
	var e float64
	for i := range want {
		d := math.Abs(got[i] - want[i])
		if want[i] != 0 {
			d /= math.Abs(want[i])
		}
		if math.IsNaN(d) {
			return math.Inf(1)
		}
		e = math.Max(e, d)
	}
	return e
}

// numSumMinusOne returns sum(v) - 1, with the sum taken exactly.
func numSumMinusOne(v []float64) float64 { return numSumMinus(v, 1) }

// numSumMinus returns sum(v) - t, computed exactly and rounded once.
func numSumMinus(v []float64, t float64) float64 {
	const prec = 4096
	sum := new(big.Float).SetPrec(prec).SetFloat64(-t)
	for _, x := range v {
		if math.IsNaN(x) || math.IsInf(x, 0) {
			return math.NaN()
		}
		sum.Add(sum, new(big.Float).SetPrec(prec).SetFloat64(x))
	}
	f, _ := sum.Float64()
	return f
}

func numFlatten(m [][]float64) []float64 {
	var out []float64
	for _, r := range m {
		out = append(out, r...)
	}
	return out
}

func numBool(b bool) float64 {
	if b {
		return 1
	}
	return 0
}

func init() {
	registerLinalgEvaluators()
	registerOptimEvaluators()
	registerPortfolioEvaluators()
	registerProxTransportEvaluators()
	registerCalculusChaosEvaluators()
	registerKnownPrecisionViolations(numericsKnownViolations)
}

// numericsKnownViolations lists the measured misses, each with its error on
// the default amd64 build (the GOAMD64=v3 build measures the same unless the
// entry says otherwise).
var numericsKnownViolations = map[string]string{
	// linalg
	"numerics/pearson/offset-1e12":               "rel err 3.1e-8: the mean of data at 1e12 rounds, and the centred sums inherit it",
	"numerics/cross/near-parallel":               "normwise rel err 5.0e-8: nearly parallel inputs, the two products of each component cancel",
	"numerics/jamesstein/offset-1e9":             "rel err 3.4e-15 (15 ulps): the grand mean of means at 1e9 rounds",
	"numerics/jamesstein/tiny-scale":             "returns c = 1 for true c = 0.0214: S = 4.7e-302 is under the absolute 1e-300 'identical means' threshold",
	"numerics/lw-identity/offset-1e5-intensity":  "abs err 5.6e-11 > 1e-11: data at 1e5 lose 7 digits in the centring",
	"numerics/lw-constcorr/offset-1e5-intensity": "abs err 5.0e-10 > 1e-11: data at 1e5 lose 7 digits in the centring",
	"numerics/mpbounds/q0.999-min":               "rel err 1.7e-13: lambdaMin = (1 - sqrt q)^2 cancels as q -> 1",
	"numerics/mpbounds/q0.99999-min":             "rel err 2.4e-12: lambdaMin = (1 - sqrt q)^2 cancels as q -> 1",
	"numerics/l2norm/underflow-1e-170":           "returns 0 for (3e-170, 4e-170): the squares underflow",
	"numerics/l2norm/subnormal-squares-1e-160":   "rel err 5.6e-6: the squares of 1e-160 are subnormal",
	"numerics/encdist/underflow-1e-170":          "returns 0 for distinct vectors: the squared differences underflow",
	"numerics/wdist/underflow-1e-170":            "returns 0 for distinct vectors: the squared differences underflow",
	"numerics/l2normalize/underflow-1e-170":      "returns false (zero magnitude) for (3e-170, 4e-170) and leaves it unnormalised",
	"numerics/cosine/underflow-1e-170":           "returns 0 (the zero-magnitude branch) for cosine 0.926: the norms underflow",
	"numerics/cosine/overflow-1e170":             "returns NaN for cosine 0.926: the dot product and norms overflow to Inf",
	"numerics/det/singular-1to9":                 "returns 6.7e-16 for an exactly singular integer matrix: the pivot test is an absolute 1e-300",
	"numerics/det/singular-rank2-covariance":     "returns -5.4e-14 for an exactly singular integer covariance: the pivot test is an absolute 1e-300",
	"numerics/inverse/singular-1to9":             "reports success (inverse entries ~4.5e15) for an exactly singular integer matrix",
	"numerics/inverse/singular-rank2-covariance": "reports success for an exactly singular integer covariance (30 of 49 such rank-2 3x3 matrices pass)",

	// optim
	"numerics/lbfgs/rosenbrock-maxiter100":     "returns (-0.949, 0.907), 1.95 from the minimizer, with no signal: the Armijo-only line search accepts steps that fail the curvature condition, so 639 of the 673 iterations it needs skip the update (with a Wolfe search: 38)",
	"numerics/bisect/tol-below-spacing-exp":    "never returns: once a and b are adjacent floats the midpoint is one of them, and b-a stays at the spacing 1.8e-15 > tol",
	"numerics/bisect/tol-below-spacing-sqrt2":  "never returns: b-a cannot fall below the spacing 2.2e-16 > tol 1e-17",
	"numerics/golden/flat-min-tol1e-12":        "returns x* + 1.05e-8: f = (x-1)^2 + 1 takes equal float values within ~1e-8 of x*, so the comparisons cannot locate x* to 1e-12",
	"numerics/golden/cosh-tol1e-10":            "returns x* + 1.66e-8: the same ~sqrt(eps) floor",
	"numerics/golden/tol-below-spacing":        "never returns: tol 1e-12 is below the spacing 1.2e-10 at x* = 1e6",
	"numerics/lerp/near-zero-crossing":         "returns 0 for -2.8e-17: y0 + (y1-y0)*(x-x0)/(x1-x0) cancels",
	"numerics/lroot/root-near-zero":            "returns 0 for -9.9e-18: x0 - y0*(x1-x0)/(y1-y0) cancels",
	"numerics/simplex/row-scaled-1e-11":        "returns the INFEASIBLE x = (0, 2), value -4, nil error (optimum -3): the ratio test ignores pivot entries below an absolute 1e-10, so the row is dropped",
	"numerics/simplex/single-row-scaled-1e-11": "returns an 'unbounded' error for an LP with optimum x = 1: its only pivot entry 1e-11 is below the absolute 1e-10 threshold",
	"numerics/simplex/costs-1e-11":             "returns x = 0, value 0 (optimum -1e-11): reduced costs above an absolute -1e-10 count as optimal",

	// optim/portfolio and optim/hrp
	"numerics/roundtrip/correlation-0.9999":                     "the round trip is off by 6.0e-12 (relative) for a nonsingular Sigma of condition 6e4",
	"numerics/roundtrip/cond-1e10":                              "the round trip is off by 1.1e-7 (relative) for a nonsingular Sigma of condition 1e10",
	"numerics/omega/hedge-view":                                 "rel err 2.8e-13: P Sigma P' cancels for a near-riskless hedge view",
	"numerics/meanvarianceweights/singular-rank2-integer":       "returns weights up to 3.2e17 for an exactly singular Sigma: the elimination's pivot test is an absolute 1e-300",
	"numerics/meanvarianceweights/singular-sample-cov-T3-N4":    "returns weights up to 3.8e19 for the exactly singular sample covariance of 3 observations of 4 assets",
	"numerics/continuouskellyweights/singular-rank2-integer":    "returns weights for an exactly singular Sigma (same elimination as MeanVarianceWeights)",
	"numerics/continuouskellyweights/singular-sample-cov-T3-N4": "returns weights for the exactly singular sample covariance of 3 observations of 4 assets",
	"numerics/bl/near-singular-perfect-correlation":             "returns (0.0273, 0.0391) where the exact posterior is (0.0233, 0.0300), 17% and 30% off, instead of nil: condition 8e16 passes LU's absolute 1e-300 pivot test",
	"numerics/projsimplex/magnitude-1e5-weights":                "weights off by 4.9e-12: theta is formed at the inputs' scale (1.2e5)",
	"numerics/projsimplex/magnitude-1e5-sum":                    "sums to 1 + 1.5e-11 for inputs near 1.2e5",
	"numerics/projsimplex/magnitude-1e8-weights":                "weights off by 9.9e-9 for inputs near 1e8",
	"numerics/projsimplex/magnitude-1e8-sum":                    "sums to 1 - 3.0e-8 for inputs near 1e8",
	"numerics/projsimplex/magnitude-1e17-weights":               "returns (0.5, 0.5) for the projection (1, 0): cumsum - 1 loses the 1 and the uniform fallback is taken",

	// optim/transport
	"numerics/sinkhorn/n10-eps0.01":         "the default 200 iterations are not enough at epsilon = 0.01*mean(C): ErrSinkhornNonConvergent; it needs 897",
	"numerics/sinkhorn/n25-eps0.01":         "the default 200 iterations are not enough at epsilon = 0.01*mean(C): ErrSinkhornNonConvergent; it needs 256",
	"numerics/sinkhorn/n25-shifted-eps0.01": "does not converge even at the internal cap of 1000 iterations",
	"numerics/wasserstein/p4-scale-1e-90":   "returns 0 for distinct samples of order 1e-90: |d|^4 underflows",
	"numerics/wasserstein/p2-scale-1e160":   "returns +Inf for samples of order 1e160: |d|^2 overflows",

	// calculus
	"numerics/deriv/sin-x1e4-h1e-5": "error 2.4e-8 > bound 3.9e-10: x+h and x-h round at x = 1e4, but the quotient divides by the nominal 2h",
	"numerics/gradient/h1e-8":       "error 8.3e7 times the stated O(h^2) bound (absolute ~1e-7): the roundoff term eps*|f|/h, which the doc does not state, dominates",
	"numerics/trapezoid/exp-n4e6":   "error 5.4e-14 > (b-a)/12*h^2*max|f^(2)| = 1.4e-14: the rounding of the n-term sum dominates",
	"numerics/simpson/exp-n1e4":     "error 5.8e-15 > (b-a)/180*h^4*max|f^(4)| = 1.5e-18: the rounding of the n-term sum dominates",
}

func registerLinalgEvaluators() {
	registerPrecisionEvaluator("linalg.PearsonCorrelation", func(c precisionCase) (float64, error) {
		return linalg.PearsonCorrelation(numVec(c, "x"), numVec(c, "y")), nil
	})
	registerPrecisionEvaluator("linalg.SpearmanCorrelation", func(c precisionCase) (float64, error) {
		return linalg.SpearmanCorrelation(numVec(c, "x"), numVec(c, "y")), nil
	})
	registerPrecisionEvaluator("linalg.Trace", func(c precisionCase) (float64, error) {
		return linalg.Trace(numVec(c, "A"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("linalg.CrossProduct", func(c precisionCase) (float64, error) {
		out := make([]float64, 3)
		linalg.CrossProduct(numVec(c, "a"), numVec(c, "b"), out)
		return numNormwiseErr(out, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("linalg.JamesSteinShrink", func(c precisionCase) (float64, error) {
		_, shrink := linalg.JamesSteinShrink(numVec(c, "means"), argF(c, "variance"))
		return shrink, nil
	})
	lw := func(f func([]float64, int, int) ([]float64, float64)) func(precisionCase) (float64, error) {
		return func(c precisionCase) (float64, error) {
			sigma, intensity := f(numVec(c, "x"), argI(c, "T"), argI(c, "N"))
			switch numStr(c, "measure") {
			case "intensity":
				return intensity, nil
			case "matrix":
				return numNormwiseErr(sigma, numVec(c, "truth")), nil
			}
			return 0, fmt.Errorf("unknown measure %q", numStr(c, "measure"))
		}
	}
	registerPrecisionEvaluator("linalg.LedoitWolfShrinkageIdentity", lw(linalg.LedoitWolfShrinkageIdentity))
	registerPrecisionEvaluator("linalg.LedoitWolfShrinkageConstantCorr", lw(linalg.LedoitWolfShrinkageConstantCorr))
	registerPrecisionEvaluator("linalg.MarchenkoPasturBounds", func(c precisionCase) (float64, error) {
		lo, hi := linalg.MarchenkoPasturBounds(argF(c, "q"))
		if numStr(c, "which") == "min" {
			return lo, nil
		}
		return hi, nil
	})
	registerPrecisionEvaluator("linalg.CleanCorrelation", func(c precisionCase) (float64, error) {
		out := linalg.CleanCorrelation(numVec(c, "corr"), argI(c, "T"), argI(c, "N"))
		return numMaxAbsErr(out, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("linalg.L2Norm", func(c precisionCase) (float64, error) {
		return linalg.L2Norm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.EncodingDistance", func(c precisionCase) (float64, error) {
		return linalg.EncodingDistance(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.DimensionWeightedDistance", func(c precisionCase) (float64, error) {
		return linalg.DimensionWeightedDistance(numVec(c, "a"), numVec(c, "b"), numVec(c, "w")), nil
	})
	registerPrecisionEvaluator("linalg.L2Normalize", func(c precisionCase) (float64, error) {
		v := numVec(c, "v")
		linalg.L2Normalize(v)
		return numExactNorm2(v), nil
	})
	registerPrecisionEvaluator("linalg.CosineSimilarity", func(c precisionCase) (float64, error) {
		return linalg.CosineSimilarity(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.DotProduct", func(c precisionCase) (float64, error) {
		return linalg.DotProduct(numVec(c, "a"), numVec(c, "b")), nil
	})
	registerPrecisionEvaluator("linalg.L1Norm", func(c precisionCase) (float64, error) {
		return linalg.L1Norm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.LInfNorm", func(c precisionCase) (float64, error) {
		return linalg.LInfNorm(numVec(c, "v")), nil
	})
	registerPrecisionEvaluator("linalg.Determinant", func(c precisionCase) (float64, error) {
		return linalg.Determinant(numVec(c, "A"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("linalg.Inverse", func(c precisionCase) (float64, error) {
		n := argI(c, "n")
		out := make([]float64, n*n)
		return numBool(linalg.Inverse(numVec(c, "A"), n, out)), nil
	})
}

// The test functions below are written so that the Go compiler cannot fuse
// their multiply-adds (an explicit float64 conversion rounds the product), so
// each is the same function on every build; only the code under test differs
// between builds.

var numFuncs1D = map[string]func(float64) float64{
	"exp":         math.Exp,
	"sin":         math.Sin,
	"x2minus2":    func(x float64) float64 { return float64(x*x) - 2 },
	"expminus1e5": func(x float64) float64 { return math.Exp(x) - 1e5 },
	"sq_xminus2": func(x float64) float64 {
		d := x - 2
		return float64(d * d)
	},
	"sq_xminus1_plus1": func(x float64) float64 {
		d := x - 1
		return float64(d*d) + 1
	},
	"cosh_xminus0.3": func(x float64) float64 { return math.Cosh(x - 0.3) },
	"sq_xminus1e6_plus1": func(x float64) float64 {
		d := x - 1e6
		return float64(d*d) + 1
	},
}

func numFunc1D(c precisionCase) func(float64) float64 {
	f, ok := numFuncs1D[numStr(c, "f")]
	if !ok {
		panic(fmt.Sprintf("%s: unknown function %q", c.ID, numStr(c, "f")))
	}
	return f
}

type numBudgetExceeded struct{}

// numWithBudget runs search with f wrapped to allow at most budget calls. A
// search still running after budget calls has not met its claimed iteration
// count (or never terminates); it is stopped by a panic and scored as NaN.
func numWithBudget(f func(float64) float64, budget int, search func(func(float64) float64) float64) (got float64) {
	calls := 0
	counted := func(x float64) float64 {
		calls++
		if calls > budget {
			panic(numBudgetExceeded{})
		}
		return f(x)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, ok := r.(numBudgetExceeded); !ok {
				panic(r)
			}
			got = math.NaN()
		}
	}()
	return search(counted)
}

func numRosenbrock(x []float64) float64 {
	a := 1 - x[0]
	b := x[1] - float64(x[0]*x[0])
	return float64(a*a) + float64(100*float64(b*b))
}

func numRosenbrockGrad(x, g []float64) {
	b := x[1] - float64(x[0]*x[0])
	g[0] = float64(-2*(1-x[0])) - float64(float64(400*x[0])*b)
	g[1] = float64(200 * b)
}

func registerOptimEvaluators() {
	registerPrecisionEvaluator("optim.LBFGS", func(c precisionCase) (float64, error) {
		var f func([]float64) float64
		var grad func([]float64, []float64)
		switch numStr(c, "problem") {
		case "rosenbrock":
			f, grad = numRosenbrock, numRosenbrockGrad
		case "quadratic":
			A, b := numVec(c, "A"), numVec(c, "b")
			n := len(b)
			ax := func(x []float64, out []float64) {
				for i := 0; i < n; i++ {
					s := 0.0
					for j := 0; j < n; j++ {
						s += float64(A[i*n+j] * x[j])
					}
					out[i] = s
				}
			}
			f = func(x []float64) float64 {
				t := make([]float64, n)
				ax(x, t)
				s := 0.0
				for i := range x {
					s += float64(x[i] * float64(0.5*t[i]-b[i]))
				}
				return s
			}
			grad = func(x, g []float64) {
				ax(x, g)
				for i := range g {
					g[i] -= b[i]
				}
			}
		default:
			return 0, fmt.Errorf("unknown problem %q", numStr(c, "problem"))
		}
		x := optim.LBFGS(f, grad, numVec(c, "x0"), argI(c, "m"), argI(c, "maxIter"), argF(c, "tol"))
		return numMaxAbsErr(x, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("optim.BisectionMethod", func(c precisionCase) (float64, error) {
		a, b, tol := argF(c, "a"), argF(c, "b"), argF(c, "tol")
		return numWithBudget(numFunc1D(c), argI(c, "budget"), func(f func(float64) float64) float64 {
			return optim.BisectionMethod(f, a, b, tol)
		}), nil
	})
	registerPrecisionEvaluator("optim.GoldenSectionSearch", func(c precisionCase) (float64, error) {
		a, b, tol := argF(c, "a"), argF(c, "b"), argF(c, "tol")
		return numWithBudget(numFunc1D(c), argI(c, "budget"), func(f func(float64) float64) float64 {
			return optim.GoldenSectionSearch(f, a, b, tol)
		}), nil
	})
	registerPrecisionEvaluator("optim.LinearInterpolate", func(c precisionCase) (float64, error) {
		return optim.LinearInterpolate(argF(c, "x0"), argF(c, "y0"), argF(c, "x1"), argF(c, "y1"), argF(c, "x")), nil
	})
	registerPrecisionEvaluator("optim.LinearInterpolateRoot", func(c precisionCase) (float64, error) {
		return optim.LinearInterpolateRoot(argF(c, "x0"), argF(c, "y0"), argF(c, "x1"), argF(c, "y1")), nil
	})
	registerPrecisionEvaluator("optim.SimplexMethod", func(c precisionCase) (float64, error) {
		cost, flat, b := numVec(c, "c"), numVec(c, "A"), numVec(c, "b")
		m, n := argI(c, "m"), len(cost)
		A := make([][]float64, m)
		for i := range A {
			A[i] = flat[i*n : (i+1)*n]
		}
		_, val, err := optim.SimplexMethod(cost, A, b)
		if err != nil {
			return math.NaN(), nil
		}
		return val, nil
	})
}

func registerPortfolioEvaluators() {
	registerPrecisionEvaluator("portfolio.ImpliedEquilibriumReturns", func(c precisionCase) (float64, error) {
		pi := portfolio.ImpliedEquilibriumReturns(numVec(c, "w"), numMat(c, "Sigma"), argF(c, "delta"))
		return numMaxRelErr(pi, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("portfolio.RoundTrip", func(c precisionCase) (float64, error) {
		w, sigma, delta := numVec(c, "w"), numMat(c, "Sigma"), argF(c, "delta")
		back := portfolio.MeanVarianceWeights(portfolio.ImpliedEquilibriumReturns(w, sigma, delta), sigma, delta)
		return numNormwiseErr(back, w), nil
	})
	registerPrecisionEvaluator("portfolio.HeLittermanOmega", func(c precisionCase) (float64, error) {
		om := portfolio.HeLittermanOmega(numMat(c, "P"), numMat(c, "Sigma"), argF(c, "tau"))
		if om == nil {
			return math.NaN(), nil
		}
		return om[0][0], nil
	})
	registerPrecisionEvaluator("portfolio.BlackLittermanPosterior", func(c precisionCase) (float64, error) {
		mu := portfolio.BlackLittermanPosterior(numVec(c, "pi"), numMat(c, "Sigma"), numMat(c, "P"), numVec(c, "Q"), numMat(c, "Omega"), argF(c, "tau"))
		if m, ok := c.Args["measure"]; ok && m == "returned" {
			return numBool(mu != nil), nil
		}
		return numMaxRelErr(mu, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("portfolio.BlackLittermanPosteriorCovariance", func(c precisionCase) (float64, error) {
		m := portfolio.BlackLittermanPosteriorCovariance(numMat(c, "Sigma"), numMat(c, "P"), numMat(c, "Omega"), argF(c, "tau"))
		return numNormwiseErr(numFlatten(m), numVec(c, "truth")), nil
	})
	weights := func(f func([]float64, [][]float64, float64) []float64) func(precisionCase) (float64, error) {
		return func(c precisionCase) (float64, error) {
			w := f(numVec(c, "mu"), numMat(c, "Sigma"), argF(c, "param"))
			switch numStr(c, "measure") {
			case "returned":
				return numBool(w != nil), nil
			case "relerr":
				return numMaxRelErr(w, numVec(c, "truth")), nil
			}
			return 0, fmt.Errorf("unknown measure %q", numStr(c, "measure"))
		}
	}
	registerPrecisionEvaluator("portfolio.MeanVarianceWeights", weights(portfolio.MeanVarianceWeights))
	registerPrecisionEvaluator("portfolio.ContinuousKellyWeights", weights(portfolio.ContinuousKellyWeights))
	registerPrecisionEvaluator("portfolio.MeanVarianceWeightsLongOnly", func(c precisionCase) (float64, error) {
		w := portfolio.MeanVarianceWeightsLongOnly(numVec(c, "mu"), numMat(c, "Sigma"), argF(c, "delta"))
		return numMaxAbsErr(w, numVec(c, "truth")), nil
	})
	registerPrecisionEvaluator("portfolio.ProjectSimplex", func(c precisionCase) (float64, error) {
		w := portfolio.ProjectSimplex(numVec(c, "v"))
		switch numStr(c, "measure") {
		case "weights":
			return numMaxAbsErr(w, numVec(c, "truth")), nil
		case "sum":
			return math.Abs(numSumMinusOne(w)), nil
		}
		return 0, fmt.Errorf("unknown measure %q", numStr(c, "measure"))
	})
	registerPrecisionEvaluator("hrp.CorrelationDistance", func(c precisionCase) (float64, error) {
		rho := argF(c, "rho")
		d, err := hrp.CorrelationDistance([][]float64{{1, rho}, {rho, 1}})
		if err != nil {
			return 0, err
		}
		return d[0][1], nil
	})
	registerPrecisionEvaluator("hrp.RecursiveBisection", func(c precisionCase) (float64, error) {
		w, err := hrp.RecursiveBisection(numMat(c, "cov"), numInts(c, "order"))
		if err != nil {
			return 0, err
		}
		return math.Abs(numSumMinusOne(w)), nil
	})
}

func registerProxTransportEvaluators() {
	registerPrecisionEvaluator("proximal.Fbs", func(c precisionCase) (float64, error) {
		A, b := numVec(c, "A"), numVec(c, "b")
		m := argI(c, "m")
		n := len(A) / m
		lambda := argF(c, "lambda")
		accel, ok := c.Args["accelerate"].(bool)
		if !ok {
			return 0, fmt.Errorf("accelerate is not a boolean")
		}
		residual := func(x []float64) []float64 {
			r := make([]float64, m)
			for i := 0; i < m; i++ {
				s := -b[i]
				for j := 0; j < n; j++ {
					s += float64(A[i*n+j] * x[j])
				}
				r[i] = s
			}
			return r
		}
		grad := func(x, out []float64) float64 {
			r := residual(x)
			for j := 0; j < n; j++ {
				s := 0.0
				for i := 0; i < m; i++ {
					s += float64(A[i*n+j] * r[i])
				}
				out[j] = s
			}
			return 0
		}
		prox := func(v []float64, gamma float64, out []float64) { proximal.ProxL1(v, gamma*lambda, out) }
		x := make([]float64, n)
		work := make([]float64, n)
		cfg := proximal.FbsConfig{Step: argF(c, "step"), MaxIter: argI(c, "iters"), AbsTol: 1e-300, Accelerate: accel}
		if _, err := proximal.Fbs(grad, prox, x, work, cfg); err != nil {
			return 0, err
		}
		obj := 0.0
		for _, ri := range residual(x) {
			obj += float64(ri * ri)
		}
		obj /= 2
		for _, xi := range x {
			obj += float64(lambda * math.Abs(xi))
		}
		return obj - argF(c, "fstar"), nil
	})
	registerPrecisionEvaluator("transport.Sinkhorn", func(c precisionCase) (float64, error) {
		a, b, cost, eps := numVec(c, "a"), numVec(c, "b"), numMat(c, "cost"), argF(c, "epsilon")
		switch numStr(c, "measure") {
		case "default-budget":
			_, err := transport.Sinkhorn(a, b, cost, eps, 0, 0)
			if err == nil {
				return 0, nil
			}
			if !errors.Is(err, transport.ErrSinkhornNonConvergent) {
				return 0, err
			}
			res, err := transport.Sinkhorn(a, b, cost, eps, 1000, 0)
			if err != nil {
				return math.Inf(1), nil
			}
			return float64(res.Iterations - 200), nil
		case "row-residual":
			res, err := transport.Sinkhorn(a, b, cost, eps, argI(c, "maxIter"), argF(c, "tol"))
			if err != nil {
				return math.NaN(), nil
			}
			total := 0.0
			for i, row := range res.Plan {
				total += math.Abs(numSumMinus(row, a[i]))
			}
			return total, nil
		}
		return 0, fmt.Errorf("unknown measure %q", numStr(c, "measure"))
	})
	registerPrecisionEvaluator("transport.Wasserstein1D", func(c precisionCase) (float64, error) {
		return transport.Wasserstein1D(numVec(c, "u"), numVec(c, "v"), argF(c, "p"))
	})
}

func registerCalculusChaosEvaluators() {
	registerPrecisionEvaluator("calculus.NumericalDerivative", func(c precisionCase) (float64, error) {
		return calculus.NumericalDerivative(numFunc1D(c), argF(c, "x"), argF(c, "h")), nil
	})
	registerPrecisionEvaluator("calculus.NumericalGradient", func(c precisionCase) (float64, error) {
		if numStr(c, "f") != "exp2d" {
			return 0, fmt.Errorf("unknown function %q", numStr(c, "f"))
		}
		f := func(x []float64) float64 { return math.Exp(x[0]) + math.Exp(2*x[1]) }
		x := numVec(c, "x")
		out := make([]float64, len(x))
		calculus.NumericalGradient(f, x, argF(c, "h"), out)
		truth, bound := numVec(c, "truth"), numVec(c, "bound")
		worst := 0.0
		for i := range out {
			worst = math.Max(worst, math.Abs(out[i]-truth[i])/bound[i])
		}
		return worst, nil
	})
	registerPrecisionEvaluator("calculus.TrapezoidalRule", func(c precisionCase) (float64, error) {
		return calculus.TrapezoidalRule(numFunc1D(c), argF(c, "a"), argF(c, "b"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("calculus.SimpsonsRule", func(c precisionCase) (float64, error) {
		return calculus.SimpsonsRule(numFunc1D(c), argF(c, "a"), argF(c, "b"), argI(c, "n")), nil
	})
	registerPrecisionEvaluator("calculus.GaussLegendre", func(c precisionCase) (float64, error) {
		coef := numVec(c, "coef")
		poly := func(x float64) float64 {
			acc := 0.0
			for _, k := range coef {
				acc = float64(acc*x) + k
			}
			return acc
		}
		return calculus.GaussLegendre(poly, argF(c, "a"), argF(c, "b"), argI(c, "points")), nil
	})
	registerPrecisionEvaluator("chaos.EulerStep", func(c precisionCase) (float64, error) {
		out := make([]float64, 1)
		chaos.EulerStep(func(_ float64, y, dydt []float64) { dydt[0] = y[0] }, 0, []float64{1}, argF(c, "dt"), out)
		return out[0], nil
	})
	registerPrecisionEvaluator("chaos.LogisticMap", func(c precisionCase) (float64, error) {
		r, x := argF(c, "r"), argF(c, "x0")
		for i := argI(c, "iters"); i > 0; i-- {
			x = chaos.LogisticMap(r, x)
		}
		return x, nil
	})
}
