package reality_test

// Precision ratchet.
//
// The files testdata/stress/precision_*.json (generated by the scripts in
// tools/stressgolden from mpmath at 60 digits) pair functions with the
// precision their own docstrings claim, at inputs where that claim is hardest
// to keep: distribution tails, large shapes, ties. Every case must meet its
// claim, except the measured violations listed in knownPrecisionViolations.
// That list is a ratchet:
//   - a listed case that now meets its claim fails the test, so the entry is
//     removed in the change that fixes it;
//   - an unlisted case that misses its claim fails the test.
// The list can therefore only shrink.
//
// Report every case with its error:
//
//	REALITY_PRECISION_REPORT=1 go test -run TestPrecisionClaims -v .
//
// To cover another area, add its own case file, testdata/stress/
// precision_<area>.json, and a test file that registers the area's evaluators
// with registerPrecisionEvaluator and its measured violations with
// registerKnownPrecisionViolations, both from init. Case ids must be unique
// across files.

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/davly/reality/combinatorics"
	"github.com/davly/reality/prob"
)

// knownPrecisionViolations maps a case id to its measured state when it was
// listed. Remove an entry in the same change that fixes it.
var knownPrecisionViolations = map[string]string{
	"ttest/tail-t20":        "p = 0 for t = 20, df = 30 (true 6.75e-19): computed as 2*(1-CDF)",
	"chisq/df99999":         "p = 0.98829 vs 0.98745 (rel 8.6e-4): incomplete-gamma iteration cap at large shape",
	"poisson/lower-tail":    "CDF(0; 40) = 0 below its own PMF (true 4.25e-18): computed as 1-P",
	"poisson/median-1e4":    "0.52488 vs 0.50266 (rel 4.4e-2): incomplete-gamma iteration cap",
	"gamma/k1e4":            "0.47858 vs 0.50133 (rel 4.5e-2): series capped at 200 iterations",
	"gamma/k1e5":            "0.23749 vs 0.50042 (rel 0.53): series capped at 200 iterations",
	"fisher/tie-9-11-10-10": "0.76363 vs exactly 1: an absolute 1e-14 tie tolerance drops an equally likely table",
	"betacdf/0.5-1e6-1e6":   "0.500313 vs exactly 1/2 (abs 3.1e-4): continued fraction capped at 200 iterations",
}

type precisionCase struct {
	ID      string         `json:"id"`
	Func    string         `json:"func"`
	Args    map[string]any `json:"args"`
	Want    float64        `json:"want"`
	Tol     float64        `json:"tol"`
	TolKind string         `json:"tol_kind"`
	Claim   string         `json:"claim"`
}

func argF(c precisionCase, k string) float64 {
	v, ok := c.Args[k].(float64)
	if !ok {
		panic(fmt.Sprintf("%s: argument %q is not a number", c.ID, k))
	}
	return v
}

func argI(c precisionCase, k string) int {
	v := argF(c, k)
	if v != math.Trunc(v) {
		panic(fmt.Sprintf("%s: argument %q is not an integer", c.ID, k))
	}
	return int(v)
}

// precisionEvaluators maps a case's "func" to the code that evaluates it.
var precisionEvaluators = map[string]func(precisionCase) (float64, error){}

// registerPrecisionEvaluator adds the evaluator for one function. Call it from
// init; a duplicate name panics.
func registerPrecisionEvaluator(name string, f func(precisionCase) (float64, error)) {
	if _, dup := precisionEvaluators[name]; dup {
		panic("duplicate precision evaluator for " + name)
	}
	precisionEvaluators[name] = f
}

// registerKnownPrecisionViolations adds an area's measured violations to
// knownPrecisionViolations. Call it from init; a duplicate id panics.
func registerKnownPrecisionViolations(m map[string]string) {
	for id, why := range m {
		if _, dup := knownPrecisionViolations[id]; dup {
			panic("duplicate known precision violation " + id)
		}
		knownPrecisionViolations[id] = why
	}
}

func evalPrecisionCase(c precisionCase) (float64, error) {
	f, ok := precisionEvaluators[c.Func]
	if !ok {
		return 0, fmt.Errorf("no evaluator for %s", c.Func)
	}
	return f(c)
}

func init() {
	registerPrecisionEvaluator("TTestOneSample", func(c precisionCase) (float64, error) {
		raw, ok := c.Args["data"].([]any)
		if !ok {
			return 0, fmt.Errorf("data is not an array")
		}
		data := make([]float64, len(raw))
		for i, v := range raw {
			data[i] = v.(float64)
		}
		_, p := prob.TTestOneSample(data, argF(c, "mu0"))
		return p, nil
	})
	registerPrecisionEvaluator("ChiSquaredTest", func(c precisionCase) (float64, error) {
		k, e, d := argI(c, "k"), argF(c, "e"), argF(c, "d")
		obs, exp := make([]float64, k), make([]float64, k)
		for i := range obs {
			exp[i] = e
			if i%2 == 0 {
				obs[i] = e + d
			} else {
				obs[i] = e - d
			}
		}
		_, p := prob.ChiSquaredTest(obs, exp)
		return p, nil
	})
	registerPrecisionEvaluator("PoissonCDF", func(c precisionCase) (float64, error) {
		return prob.PoissonCDF(argI(c, "k"), argF(c, "lambda")), nil
	})
	registerPrecisionEvaluator("GammaCDF", func(c precisionCase) (float64, error) {
		return prob.GammaCDF(argF(c, "x"), argF(c, "k"), argF(c, "theta")), nil
	})
	registerPrecisionEvaluator("NormalQuantile", func(c precisionCase) (float64, error) {
		return prob.NormalQuantile(argF(c, "p"), 0, 1), nil
	})
	registerPrecisionEvaluator("ExponentialQuantile", func(c precisionCase) (float64, error) {
		return prob.ExponentialQuantile(argF(c, "p"), argF(c, "lambda")), nil
	})
	registerPrecisionEvaluator("ProportionBayesFactor10", func(c precisionCase) (float64, error) {
		bf, _ := prob.ProportionBayesFactor10(argI(c, "k"), argI(c, "n"))
		return bf, nil
	})
	registerPrecisionEvaluator("BinomialCoeff", func(c precisionCase) (float64, error) {
		return combinatorics.BinomialCoeff(argI(c, "n"), argI(c, "k")), nil
	})
	registerPrecisionEvaluator("Factorial", func(c precisionCase) (float64, error) {
		return combinatorics.Factorial(argI(c, "n")), nil
	})
	registerPrecisionEvaluator("FisherExactTest", func(c precisionCase) (float64, error) {
		return prob.FisherExactTest(argI(c, "a"), argI(c, "b"), argI(c, "c"), argI(c, "d")), nil
	})
	registerPrecisionEvaluator("BetaCDF", func(c precisionCase) (float64, error) {
		return prob.BetaCDF(argF(c, "x"), argF(c, "alpha"), argF(c, "beta")), nil
	})
}

// precisionError returns the error measure the case's claim is stated in.
func precisionError(c precisionCase, got float64) float64 {
	if math.IsNaN(got) || math.IsInf(got, 0) {
		return math.Inf(1)
	}
	diff := math.Abs(got - c.Want)
	if c.TolKind == "abs" || c.Want == 0 {
		return diff
	}
	return diff / math.Abs(c.Want)
}

func TestPrecisionClaims(t *testing.T) {
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	files, err := filepath.Glob(filepath.Join(root, "testdata", "stress", "precision_*.json"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no testdata/stress/precision_*.json case files")
	}
	sort.Strings(files)
	var cases []precisionCase
	for _, path := range files {
		data, err := os.ReadFile(path) // #nosec G304 -- case files inside this module
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var doc struct {
			Cases []precisionCase `json:"cases"`
		}
		if err := json.Unmarshal(data, &doc); err != nil {
			t.Fatalf("parsing %s: %v", path, err)
		}
		if len(doc.Cases) == 0 {
			t.Fatalf("%s has no cases: the generator output is empty", path)
		}
		cases = append(cases, doc.Cases...)
	}

	report := os.Getenv("REALITY_PRECISION_REPORT") != ""
	seen := map[string]bool{}
	for _, c := range cases {
		if seen[c.ID] {
			t.Fatalf("duplicate case id %s", c.ID)
		}
		seen[c.ID] = true
		if c.TolKind != "rel" && c.TolKind != "abs" {
			t.Fatalf("%s: unknown tol_kind %q", c.ID, c.TolKind)
		}
		got, err := evalPrecisionCase(c)
		if err != nil {
			t.Errorf("%s: %v", c.ID, err)
			continue
		}
		e := precisionError(c, got)
		meets := e <= c.Tol
		_, listed := knownPrecisionViolations[c.ID]
		if report {
			status := "meets claim"
			if !meets {
				status = "VIOLATES claim"
			}
			t.Logf("%-30s %-15s got %-24.17g want %-24.17g %s err %.3g (tol %.3g)", c.ID, status, got, c.Want, c.TolKind, e, c.Tol)
		}
		switch {
		case meets && listed:
			t.Errorf("%s now meets its claim (%s err %.3g <= %.3g): remove it from knownPrecisionViolations", c.ID, c.TolKind, e, c.Tol)
		case !meets && !listed:
			t.Errorf("%s violates its documented precision: got %.17g, want %.17g (%s err %.3g > %.3g)\n  claim: %s", c.ID, got, c.Want, c.TolKind, e, c.Tol, c.Claim)
		}
	}
	var stale []string
	for id := range knownPrecisionViolations {
		if !seen[id] {
			stale = append(stale, id)
		}
	}
	sort.Strings(stale)
	if len(stale) > 0 {
		t.Errorf("knownPrecisionViolations lists cases that no longer exist: %v", stale)
	}
}

// TestPrecisionRegistryRejectsDuplicates checks that two area files cannot
// silently shadow each other's evaluators or listed violations.
func TestPrecisionRegistryRejectsDuplicates(t *testing.T) {
	mustPanic := func(what string, f func()) {
		t.Helper()
		defer func() {
			if recover() == nil {
				t.Errorf("a duplicate %s was accepted", what)
			}
		}()
		f()
	}
	mustPanic("evaluator", func() {
		registerPrecisionEvaluator("GammaCDF", func(precisionCase) (float64, error) { return 0, nil })
	})
	const id = "test/registry-duplicate"
	registerKnownPrecisionViolations(map[string]string{id: "registered by this test"})
	defer delete(knownPrecisionViolations, id)
	mustPanic("listed violation", func() {
		registerKnownPrecisionViolations(map[string]string{id: "registered twice"})
	})
}
