package reality_test

// Precision claims of the applied-formula packages: physics, fluids, em,
// acoustics and color.
//
// The cases live in testdata/stress/precision_applied.json, generated by
// tools/stressgolden/applied.py: each pairs a function with the precision its
// own docstring promises and an input where that promise is hardest to keep.
// This file registers the evaluators that call the functions, and lists in
// appliedKnownViolations the cases that measurably miss their claim, with the
// measured error. TestPrecisionClaims (precision_test.go) fails on any
// unlisted miss and on any listed case that starts to meet its claim, so the
// list can only shrink.
//
// Case ids read applied/<function>-<class>-<name>. The classes are typ
// (typical input), hard (hard input), extreme (an intermediate product
// overflows or underflows although the result is representable) and cond
// (ill-conditioned: any float64 evaluation of the formula loses this much).

import (
	"fmt"
	"math"
	"strings"

	"github.com/davly/reality/acoustics"
	"github.com/davly/reality/color"
	"github.com/davly/reality/em"
	"github.com/davly/reality/fluids"
	"github.com/davly/reality/physics"
)

// regF registers the evaluator of a function of float arguments. keys names
// the arguments in call order, separated by spaces; they are the parameter
// names in the case file.
func regF(name, keys string, f func(a []float64) float64) {
	ks := strings.Fields(keys)
	registerPrecisionEvaluator(name, func(c precisionCase) (float64, error) {
		a := make([]float64, len(ks))
		for i, k := range ks {
			a[i] = argF(c, k)
		}
		return f(a), nil
	})
}

// appliedList reads a resistor list from a case: an explicit array "r", or
// "count" copies of "value" (so a long list need not be written out).
func appliedList(c precisionCase) ([]float64, error) {
	if raw, ok := c.Args["r"].([]any); ok {
		out := make([]float64, len(raw))
		for i, v := range raw {
			f, ok := v.(float64)
			if !ok {
				return nil, fmt.Errorf("r[%d] is not a number", i)
			}
			out[i] = f
		}
		return out, nil
	}
	out := make([]float64, argI(c, "count"))
	for i := range out {
		out[i] = argF(c, "value")
	}
	return out, nil
}

// heatTruncation returns the truncation error per unit time of one step of
// physics.HeatEquation1DStep on the discrete sine mode sin(pi x_i), x_i =
// i/(n-1), measured at the midpoint node. The mode is an exact eigenvector of
// the three-point stencil, so the step multiplies it by one factor g, and the
// exact heat equation multiplies it by exp(-alpha pi^2 dt): the difference,
// divided by dt, is the truncation error per unit time. Its expansion is
// alpha pi^4 dx^2 / 12 - alpha^2 pi^4 dt / 2 + ..., so it is first order in
// dt and second order in dx exactly when the documented orders hold.
func heatTruncation(n int, alpha, dt float64) float64 {
	dx := 1 / float64(n-1)
	u := make([]float64, n)
	out := make([]float64, n)
	for i := 1; i < n-1; i++ {
		u[i] = math.Sin(math.Pi * float64(i) * dx)
	}
	physics.HeatEquation1DStep(u, dt, dx, alpha, out)
	mid := n / 2
	return (out[mid]/u[mid] - math.Exp(-alpha*math.Pi*math.Pi*dt)) / dt
}

func init() {
	// acoustics
	regF("acoustics.SoundSpeed", "gamma R T M", func(a []float64) float64 { return acoustics.SoundSpeed(a[0], a[1], a[2], a[3]) })
	regF("acoustics.SoundIntensity", "P r", func(a []float64) float64 { return acoustics.SoundIntensity(a[0], a[1]) })
	regF("acoustics.DecibelSPL", "p pRef", func(a []float64) float64 { return acoustics.DecibelSPL(a[0], a[1]) })
	regF("acoustics.DecibelFromIntensity", "I IRef", func(a []float64) float64 { return acoustics.DecibelFromIntensity(a[0], a[1]) })
	regF("acoustics.SabineRT60", "V A", func(a []float64) float64 { return acoustics.SabineRT60(a[0], a[1]) })
	regF("acoustics.DopplerShift", "f0 vs vr c", func(a []float64) float64 { return acoustics.DopplerShift(a[0], a[1], a[2], a[3]) })
	registerPrecisionEvaluator("acoustics.ResonantFrequency", func(c precisionCase) (float64, error) {
		return acoustics.ResonantFrequency(argF(c, "L"), argI(c, "n"), argF(c, "c")), nil
	})
	regF("acoustics.WaveLength", "f c", func(a []float64) float64 { return acoustics.WaveLength(a[0], a[1]) })
	regF("acoustics.AWeighting", "f", func(a []float64) float64 { return acoustics.AWeighting(a[0]) })

	// em
	regF("em.CoulombForce", "q1 q2 r", func(a []float64) float64 { return em.CoulombForce(a[0], a[1], a[2]) })
	regF("em.ElectricField", "q r", func(a []float64) float64 { return em.ElectricField(a[0], a[1]) })
	regF("em.OhmsLaw", "V R", func(a []float64) float64 { return em.OhmsLaw(a[0], a[1]) })
	regF("em.PowerElectric", "V I", func(a []float64) float64 { return em.PowerElectric(a[0], a[1]) })
	registerPrecisionEvaluator("em.ResistorsInSeries", func(c precisionCase) (float64, error) {
		r, err := appliedList(c)
		return em.ResistorsInSeries(r), err
	})
	registerPrecisionEvaluator("em.ResistorsInParallel", func(c precisionCase) (float64, error) {
		r, err := appliedList(c)
		return em.ResistorsInParallel(r), err
	})
	regF("em.CapacitorEnergy", "C V", func(a []float64) float64 { return em.CapacitorEnergy(a[0], a[1]) })
	regF("em.InductorEnergy", "L I", func(a []float64) float64 { return em.InductorEnergy(a[0], a[1]) })
	regF("em.RCTimeConstant", "R C", func(a []float64) float64 { return em.RCTimeConstant(a[0], a[1]) })
	regF("em.ResonantFrequencyLC", "L C", func(a []float64) float64 { return em.ResonantFrequencyLC(a[0], a[1]) })

	// fluids
	regF("fluids.ReynoldsNumber", "rho v L mu", func(a []float64) float64 { return fluids.ReynoldsNumber(a[0], a[1], a[2], a[3]) })
	regF("fluids.BernoulliPressure", "rho v1 p1 h1 v2 h2 g", func(a []float64) float64 {
		return fluids.BernoulliPressure(a[0], a[1], a[2], a[3], a[4], a[5], a[6])
	})
	regF("fluids.PipeFlowFriction", "Re roughness diameter", func(a []float64) float64 { return fluids.PipeFlowFriction(a[0], a[1], a[2]) })
	regF("fluids.DarcyWeisbach", "f L D rho v", func(a []float64) float64 { return fluids.DarcyWeisbach(a[0], a[1], a[2], a[3], a[4]) })
	regF("fluids.DragForce", "Cd rho v A", func(a []float64) float64 { return fluids.DragForce(a[0], a[1], a[2], a[3]) })
	regF("fluids.LiftForce", "Cl rho v A", func(a []float64) float64 { return fluids.LiftForce(a[0], a[1], a[2], a[3]) })
	regF("fluids.TerminalVelocity", "m g Cd rho A", func(a []float64) float64 { return fluids.TerminalVelocity(a[0], a[1], a[2], a[3], a[4]) })
	regF("fluids.StokesLaw", "mu r v", func(a []float64) float64 { return fluids.StokesLaw(a[0], a[1], a[2]) })
	regF("fluids.MassFlowRate", "rho v A", func(a []float64) float64 { return fluids.MassFlowRate(a[0], a[1], a[2]) })
	regF("fluids.VolumetricFlowRate", "v A", func(a []float64) float64 { return fluids.VolumetricFlowRate(a[0], a[1]) })

	// physics: mechanics
	regF("physics.NewtonSecondLaw", "F m", func(a []float64) float64 { return physics.NewtonSecondLaw(a[0], a[1]) })
	regF("physics.ProjectilePosition.x", "v0 theta t g", func(a []float64) float64 {
		x, _ := physics.ProjectilePosition(a[0], a[1], a[2], a[3])
		return x
	})
	regF("physics.ProjectilePosition.y", "v0 theta t g", func(a []float64) float64 {
		_, y := physics.ProjectilePosition(a[0], a[1], a[2], a[3])
		return y
	})
	regF("physics.GravitationalForce", "m1 m2 r", func(a []float64) float64 { return physics.GravitationalForce(a[0], a[1], a[2]) })
	regF("physics.OrbitalVelocity", "M r", func(a []float64) float64 { return physics.OrbitalVelocity(a[0], a[1]) })
	regF("physics.SpringForce", "k x c v", func(a []float64) float64 { return physics.SpringForce(a[0], a[1], a[2], a[3]) })
	regF("physics.ElasticCollision.v1f", "m1 v1 m2 v2", func(a []float64) float64 {
		v1f, _ := physics.ElasticCollision(a[0], a[1], a[2], a[3])
		return v1f
	})
	regF("physics.ElasticCollision.v2f", "m1 v1 m2 v2", func(a []float64) float64 {
		_, v2f := physics.ElasticCollision(a[0], a[1], a[2], a[3])
		return v2f
	})
	regF("physics.Pendulum", "theta L g damping", func(a []float64) float64 { return physics.Pendulum(a[0], a[1], a[2], a[3]) })
	regF("physics.KineticEnergy", "m v", func(a []float64) float64 { return physics.KineticEnergy(a[0], a[1]) })
	regF("physics.PotentialEnergy", "m g h", func(a []float64) float64 { return physics.PotentialEnergy(a[0], a[1], a[2]) })

	// physics: materials
	regF("physics.HookesLaw", "E epsilon", func(a []float64) float64 { return physics.HookesLaw(a[0], a[1]) })
	regF("physics.VonMisesStress", "s1 s2 s3", func(a []float64) float64 { return physics.VonMisesStress(a[0], a[1], a[2]) })
	regF("physics.TrescaStress", "s1 s2 s3", func(a []float64) float64 { return physics.TrescaStress(a[0], a[1], a[2]) })
	regF("physics.StressIntensityFactor", "sigma a Y", func(a []float64) float64 { return physics.StressIntensityFactor(a[0], a[1], a[2]) })
	regF("physics.GriffithCriterion", "E gamma a", func(a []float64) float64 { return physics.GriffithCriterion(a[0], a[1], a[2]) })
	regF("physics.ParisLaw", "C m deltaK", func(a []float64) float64 { return physics.ParisLaw(a[0], a[1], a[2]) })
	registerPrecisionEvaluator("physics.CoffinManson", func(c precisionCase) (float64, error) {
		return physics.CoffinManson(argF(c, "epsilonF"), argF(c, "c"), argI(c, "Nf")), nil
	})
	regF("physics.CreepArrhenius", "A Q R T sigma n", func(a []float64) float64 {
		return physics.CreepArrhenius(a[0], a[1], a[2], a[3], a[4], a[5])
	})
	regF("physics.CompositeMixture", "Vf Ef Em", func(a []float64) float64 { return physics.CompositeMixture(a[0], a[1], a[2]) })
	regF("physics.EulerBuckling", "E I L K", func(a []float64) float64 { return physics.EulerBuckling(a[0], a[1], a[2], a[3]) })
	regF("physics.BeamDeflection", "P L E I", func(a []float64) float64 { return physics.BeamDeflection(a[0], a[1], a[2], a[3]) })

	// physics: thermodynamics
	regF("physics.IdealGas", "n T V", func(a []float64) float64 { return physics.IdealGas(a[0], a[1], a[2]) })
	regF("physics.StefanBoltzmann", "T A emissivity", func(a []float64) float64 { return physics.StefanBoltzmann(a[0], a[1], a[2]) })
	regF("physics.CarnotEfficiency", "Th Tc", func(a []float64) float64 { return physics.CarnotEfficiency(a[0], a[1]) })
	regF("physics.FourierHeatConduction", "k A dTdx", func(a []float64) float64 { return physics.FourierHeatConduction(a[0], a[1], a[2]) })
	regF("physics.NewtonCooling", "h A Ts Tinf", func(a []float64) float64 { return physics.NewtonCooling(a[0], a[1], a[2], a[3]) })
	regF("physics.ThermalExpansion", "L0 alpha deltaT", func(a []float64) float64 { return physics.ThermalExpansion(a[0], a[1], a[2]) })
	registerPrecisionEvaluator("physics.HeatEquation1DStep.order_dt", func(c precisionCase) (float64, error) {
		n, alpha, dt := argI(c, "n"), argF(c, "alpha"), argF(c, "dt")
		t1, t2, t3 := heatTruncation(n, alpha, dt), heatTruncation(n, alpha, dt/2), heatTruncation(n, alpha, dt/4)
		return math.Log2((t1 - t2) / (t2 - t3)), nil
	})
	registerPrecisionEvaluator("physics.HeatEquation1DStep.order_dx", func(c precisionCase) (float64, error) {
		n, alpha, dt := argI(c, "n"), argF(c, "alpha"), argF(c, "dt")
		// Richardson extrapolation in dt removes the O(dt) term of the truncation error.
		coarse := 2*heatTruncation(n, alpha, dt/2) - heatTruncation(n, alpha, dt)
		fine := 2*heatTruncation(2*n-1, alpha, dt/2) - heatTruncation(2*n-1, alpha, dt)
		return math.Log2(coarse / fine), nil
	})

	// physics: optics
	regF("physics.SnellRefraction", "n1 n2 thetaI", func(a []float64) float64 { return physics.SnellRefraction(a[0], a[1], a[2]) })
	regF("physics.FresnelReflectance", "n1 n2 thetaI", func(a []float64) float64 { return physics.FresnelReflectance(a[0], a[1], a[2]) })
	regF("physics.BeerLambertLaw", "I0 mu x", func(a []float64) float64 { return physics.BeerLambertLaw(a[0], a[1], a[2]) })

	// color
	for i, nm := range []string{"X", "Y", "Z"} {
		i := i
		regF("color.LinearRGBToXYZ."+nm, "r g b", func(a []float64) float64 {
			x, y, z := color.LinearRGBToXYZ(a[0], a[1], a[2])
			return [3]float64{x, y, z}[i]
		})
		regF("color.BradfordAdapt."+nm, "X Y Z srcWPx srcWPy dstWPx dstWPy", func(a []float64) float64 {
			x, y, z := color.BradfordAdapt(a[0], a[1], a[2], a[3], a[4], a[5], a[6])
			return [3]float64{x, y, z}[i]
		})
		regF("color.LabToXYZ."+nm, "L a b Xn Yn Zn", func(a []float64) float64 {
			x, y, z := color.LabToXYZ(a[0], a[1], a[2], a[3], a[4], a[5])
			return [3]float64{x, y, z}[i]
		})
	}
	for i, nm := range []string{"r", "g", "b"} {
		i := i
		regF("color.XYZToLinearRGB."+nm, "X Y Z", func(a []float64) float64 {
			r, g, b := color.XYZToLinearRGB(a[0], a[1], a[2])
			return [3]float64{r, g, b}[i]
		})
		regF("color.HSVToRGB."+nm, "h s v", func(a []float64) float64 {
			r, g, b := color.HSVToRGB(a[0], a[1], a[2])
			return [3]float64{r, g, b}[i]
		})
		regF("color.ToneMapReinhard."+nm, "r g b wp", func(a []float64) float64 {
			r, g, b := color.ToneMapReinhard(a[0], a[1], a[2], a[3])
			return [3]float64{r, g, b}[i]
		})
	}
	for i, nm := range []string{"L", "a", "b"} {
		i := i
		regF("color.XYZToLab."+nm, "X Y Z Xn Yn Zn", func(a []float64) float64 {
			l, aa, bb := color.XYZToLab(a[0], a[1], a[2], a[3], a[4], a[5])
			return [3]float64{l, aa, bb}[i]
		})
	}
	for i, nm := range []string{"h", "s"} {
		i := i
		regF("color.RGBToHSV."+nm, "r g b", func(a []float64) float64 {
			h, s, v := color.RGBToHSV(a[0], a[1], a[2])
			return [3]float64{h, s, v}[i]
		})
	}
	regF("color.RGBToHSV.h_below_360", "r g b", func(a []float64) float64 {
		if h, _, _ := color.RGBToHSV(a[0], a[1], a[2]); h < 360 {
			return 1
		}
		return 0
	})
	for i, nm := range []string{"X", "Y", "Z"} {
		i := i
		regF("color.BlackbodyToXYZ."+nm, "T", func(a []float64) float64 {
			x, y, z := color.BlackbodyToXYZ(a[0])
			return [3]float64{x, y, z}[i]
		})
	}
	regF("color.DeltaE76", "L1 a1 b1 L2 a2 b2", func(a []float64) float64 { return color.DeltaE76(a[0], a[1], a[2], a[3], a[4], a[5]) })
	regF("color.DeltaE2000", "L1 a1 b1 L2 a2 b2", func(a []float64) float64 { return color.DeltaE2000(a[0], a[1], a[2], a[3], a[4], a[5]) })

	registerKnownPrecisionViolations(appliedKnownViolations)
}

// appliedKnownViolations lists the applied-area cases that measurably miss
// their claim, each with the measured error. Remove an entry in the change
// that fixes it.
var appliedKnownViolations = map[string]string{
	"applied/aweight-extreme-f4-overflow":                          "f2*f2 overflows, ra is Inf/Inf and the level is NaN [got nan, want -3035]",
	"applied/aweight-extreme-f4-underflow":                         "f2*f2 underflows, ra is 0 and the level is -Inf [got -inf, want -6549]",
	"applied/aweight-hard-near-zero-1khz":                          "the level is a 0 dB crossing, where 20*log10(ra)+2.00 cancels: absolute error 1.6e-16 dB but relative error large [rel error 5.14e-08 vs claim 1e-11]",
	"applied/beer-hard-optical-depth-258-worst-rounding":           "-mu*x is rounded once (1.1e-16 relative) and exp multiplies that by the optical depth [rel error 2.73e-14 vs claim 1e-14]",
	"applied/beer-hard-optical-depth-513-worst-rounding":           "-mu*x is rounded once (1.1e-16 relative) and exp multiplies that by the optical depth [rel error 5.59e-14 vs claim 1e-14]",
	"applied/bernoulli-hard-height-cancels-speed":                  "the pressure and the height term nearly cancel in the sum [rel error 5.86e-14 vs claim 9.99e-16]",
	"applied/bernoulli-hard-near-equal-speeds-gauge-zero":          "v1*v1 - v2*v2 cancels for nearly equal speeds (the form (v1-v2)*(v1+v2) does not) [rel error 9.33e-11 vs claim 9.99e-16]",
	"applied/bernoulli-hard-static-pressure-nearly-cancels":        "the static pressure and the dynamic term nearly cancel in the sum [rel error 9.14e-14 vs claim 9.99e-16]",
	"applied/blackbody-Y-extreme-below-26k-0.1k":                   "below 26 K every term has exp(hc/(lambda k T)) > 709 and is skipped, so the result is all zeros, not Y = 1 [got 0, want 1]",
	"applied/blackbody-Y-extreme-below-26k-10k":                    "below 26 K every term has exp(hc/(lambda k T)) > 709 and is skipped, so the result is all zeros, not Y = 1 [got 0, want 1]",
	"applied/blackbody-Y-extreme-below-26k-25k":                    "below 26 K every term has exp(hc/(lambda k T)) > 709 and is skipped, so the result is all zeros, not Y = 1 [got 0, want 1]",
	"applied/bradford-X-hard-dark":                                 "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.69e-08 vs claim 1e-14]",
	"applied/bradford-X-hard-same-white-identity":                  "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 8.62e-09 vs claim 1e-14]",
	"applied/bradford-X-hard-same-white-identity-2":                "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.05e-08 vs claim 1e-14]",
	"applied/bradford-X-typ-d50-to-d65-teal":                       "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 6.67e-08 vs claim 1e-14]",
	"applied/bradford-X-typ-d65-to-d50-orange":                     "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 2.48e-08 vs claim 1e-14]",
	"applied/bradford-X-typ-d65-to-d50-white":                      "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.07e-08 vs claim 1e-14]",
	"applied/bradford-X-typ-illuminant-a-to-d65":                   "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 5.92e-08 vs claim 1e-14]",
	"applied/bradford-Y-hard-dark":                                 "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 2.28e-08 vs claim 1e-14]",
	"applied/bradford-Y-hard-same-white-identity":                  "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.8e-08 vs claim 1e-14]",
	"applied/bradford-Y-hard-same-white-identity-2":                "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 6.68e-08 vs claim 1e-14]",
	"applied/bradford-Y-typ-d50-to-d65-teal":                       "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 8.64e-09 vs claim 1e-14]",
	"applied/bradford-Y-typ-d65-to-d50-orange":                     "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 5.86e-08 vs claim 1e-14]",
	"applied/bradford-Y-typ-d65-to-d50-white":                      "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 3.61e-08 vs claim 1e-14]",
	"applied/bradford-Y-typ-illuminant-a-to-d65":                   "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 9.04e-09 vs claim 1e-14]",
	"applied/bradford-Z-hard-dark":                                 "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 3.74e-08 vs claim 1e-14]",
	"applied/bradford-Z-hard-same-white-identity":                  "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 3.35e-08 vs claim 1e-14]",
	"applied/bradford-Z-hard-same-white-identity-2":                "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 3.92e-07 vs claim 1e-14]",
	"applied/bradford-Z-typ-d50-to-d65-teal":                       "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.75e-08 vs claim 1e-14]",
	"applied/bradford-Z-typ-d65-to-d50-orange":                     "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 3.46e-07 vs claim 1e-14]",
	"applied/bradford-Z-typ-d65-to-d50-white":                      "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 6.54e-08 vs claim 1e-14]",
	"applied/bradford-Z-typ-illuminant-a-to-d65":                   "the inverse Bradford matrix is a 7-digit table, not the exact inverse: even the same white point moves a colour [rel error 1.87e-08 vs claim 1e-14]",
	"applied/carnot-hard-gradient-100mk":                           "1 - Tc/Th cancels when Tc is near Th; (Th-Tc)/Th does not [rel error 4.39e-15 vs claim 2.22e-16]",
	"applied/carnot-hard-gradient-1k":                              "1 - Tc/Th cancels when Tc is near Th; (Th-Tc)/Th does not [rel error 1.03e-14 vs claim 2.22e-16]",
	"applied/carnot-hard-gradient-1uk":                             "1 - Tc/Th cancels when Tc is near Th; (Th-Tc)/Th does not [rel error 1.47e-08 vs claim 2.22e-16]",
	"applied/carnot-hard-ocean-thermal":                            "1 - Tc/Th cancels when Tc is near Th; (Th-Tc)/Th does not [rel error 4.14e-16 vs claim 2.22e-16]",
	"applied/collision-v1-hard-first-body-stops":                   "(m1-m2)*v1 and 2*m2*v2 cancel when the first body stops dead [got 0, want 9.516e-18]",
	"applied/collision-v2-hard-second-body-stops":                  "(m2-m1)*v2 and 2*m1*v1 cancel when the second body stops dead [got 0, want -8.689e-18]",
	"applied/coulomb-extreme-huge-charges-overflow":                "k*q1*q2 overflows to +Inf before the division by r*r [got inf, want 8.988e+29]",
	"applied/coulomb-extreme-tiny-charges-underflow":               "k*q1*q2 underflows to 0 before the division by r*r [got 0, want 8.988e-131]",
	"applied/creep-hard-activation-ratio-258-worst-rounding":       "Q/(R*T) is rounded twice and exp multiplies that relative error by the exponent [rel error 5.54e-14 vs claim 1e-14]",
	"applied/creep-hard-activation-ratio-513-worst-rounding":       "Q/(R*T) is rounded twice and exp multiplies that relative error by the exponent [rel error 1.11e-13 vs claim 1e-14]",
	"applied/de2000-hard-opposite-hue-exact-a":                     "the hue difference is exactly 180 degrees and rounding in the +360 wrap of the hue sends it to the other branch (sign of dH', hue mean shifted by 180) [got 88.51, want 55.58]",
	"applied/de2000-hard-opposite-hue-exact-b":                     "the hue difference is exactly 180 degrees and rounding in the +360 wrap of the hue sends it to the other branch (sign of dH', hue mean shifted by 180) [got 90.85, want 58.05]",
	"applied/de2000-hard-opposite-hue-exact-c":                     "the hue difference is exactly 180 degrees and rounding in the +360 wrap of the hue sends it to the other branch (sign of dH', hue mean shifted by 180) [got 85.84, want 53.43]",
	"applied/de2000-hard-opposite-hue-exact-d":                     "the hue difference is exactly 180 degrees and rounding in the +360 wrap of the hue sends it to the other branch (sign of dH', hue mean shifted by 180) [got 85.09, want 53.2]",
	"applied/de2000-hard-opposite-hue-exact-lightness-differs":     "the hue difference is exactly 180 degrees and rounding in the +360 wrap of the hue sends it to the other branch (sign of dH', hue mean shifted by 180) [got 104.9, want 86.86]",
	"applied/fresnel-cond-near-critical-1e-12":                     "ill-conditioned: sqrt(1 - sin(thetaT)^2) amplifies the rounding of sin(thetaT) near the critical angle [rel error 5.24e-10 vs claim 1e-14]",
	"applied/fresnel-cond-near-critical-1e-14":                     "ill-conditioned: sqrt(1 - sin(thetaT)^2) amplifies the rounding of sin(thetaT) near the critical angle [rel error 3.25e-09 vs claim 1e-14]",
	"applied/fresnel-hard-index-matched-1e-4":                      "n1*cos(thetaI) - n2*cos(thetaT) cancels when the indices nearly match (the form (n1-n2)*(n1+n2)/(...) does not) [rel error 9.59e-13 vs claim 1e-14]",
	"applied/fresnel-hard-index-matched-1e-6":                      "n1*cos(thetaI) - n2*cos(thetaT) cancels when the indices nearly match (the form (n1-n2)*(n1+n2)/(...) does not) [rel error 1.24e-11 vs claim 1e-14]",
	"applied/fresnel-hard-index-matched-1e-6-steep":                "n1*cos(thetaI) - n2*cos(thetaT) cancels when the indices nearly match (the form (n1-n2)*(n1+n2)/(...) does not) [rel error 6.26e-11 vs claim 1e-14]",
	"applied/gravity-extreme-masses-overflow":                      "G*m1*m2 overflows to +Inf before the division by r*r [got inf, want 6.674e+189]",
	"applied/gravity-extreme-masses-underflow":                     "G*m1*m2 underflows to 0 before the division by r*r [got 0, want 6.674e-211]",
	"applied/hsv2rgb-b-hard-near-primary-green-120.001deg":         "1-|mod(h/60,2)-1| cancels for a hue next to a primary: the small channel has an absolute error of about 1e-16 [rel error 1.78e-12 vs claim 7.77e-16]",
	"applied/hsv2rgb-b-hard-nearly-saturated-1e-5":                 "v - v*s cancels for a saturation near 1: the smallest channel is v(1-s), whose rounding error is 1e-16 absolute [rel error 1.59e-12 vs claim 7.77e-16]",
	"applied/hsv2rgb-g-hard-near-primary-blue-239.999deg":          "1-|mod(h/60,2)-1| cancels for a hue next to a primary: the small channel has an absolute error of about 1e-16 [rel error 1.78e-12 vs claim 7.77e-16]",
	"applied/hsv2rgb-g-hard-near-primary-red-0.001deg":             "1-|mod(h/60,2)-1| cancels for a hue next to a primary: the small channel has an absolute error of about 1e-16 [rel error 1.1e-13 vs claim 7.77e-16]",
	"applied/hsv2rgb-g-hard-nearly-saturated-1e-13":                "v - v*s cancels for a saturation near 1: the smallest channel is v(1-s), whose rounding error is 1e-16 absolute [rel error 0.000123 vs claim 7.77e-16]",
	"applied/hsv2rgb-r-hard-hue-245-worst-rounding":                "h/60 rounds and 1-|mod(h/60,2)-1| cancels for a hue near a primary [rel error 5e-15 vs claim 7.77e-16]",
	"applied/hsv2rgb-r-hard-near-primary-blue-240.001deg":          "1-|mod(h/60,2)-1| cancels for a hue next to a primary: the small channel has an absolute error of about 1e-16 [rel error 2.49e-11 vs claim 7.77e-16]",
	"applied/hsv2rgb-r-hard-nearly-saturated-1e-9":                 "v - v*s cancels for a saturation near 1: the smallest channel is v(1-s), whose rounding error is 1e-16 absolute [rel error 4.76e-08 vs claim 7.77e-16]",
	"applied/lab2xyz-X-hard-dark-L-0.01":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 5.62e-14 vs claim 1e-14]",
	"applied/lab2xyz-X-hard-dark-L-1e-4":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 1.1e-11 vs claim 1e-14]",
	"applied/lab2xyz-Y-hard-dark-L-0.01":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 3.43e-14 vs claim 1e-14]",
	"applied/lab2xyz-Y-hard-dark-L-1e-4":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 1e-12 vs claim 1e-14]",
	"applied/lab2xyz-Z-hard-dark-L-0.01":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 8.71e-14 vs claim 1e-14]",
	"applied/lab2xyz-Z-hard-dark-L-1e-4":                           "fY - 4/29 cancels for L below 8 (linear branch of the inverse), losing digits as L falls [rel error 2.52e-12 vs claim 1e-14]",
	"applied/lc-extreme-lc-overflow":                               "L*C overflows to +Inf, so the frequency is 0 [got 0, want 1.592e-201]",
	"applied/lc-extreme-lc-underflow":                              "L*C underflows to 0, so the frequency is +Inf [got inf, want 1.592e+199]",
	"applied/orbitalv-extreme-gm-over-r-overflow":                  "G*M/r overflows to +Inf before the square root [got inf, want 8.17e+294]",
	"applied/projectile-y-hard-landing-cancellation":               "v0*sin(theta)*t and g*t^2/2 cancel at the landing time [got 0, want -2.289e-14]",
	"applied/rgb2hsv-range-hard-red-with-blue-one-ulp-above-green": "the exact hue is just below 360 but rounds to 360.0 [got 0, want 1]",
	"applied/rgb2hsv-range-hard-red-with-tiny-blue-1e-17":          "the exact hue is just below 360 but rounds to 360.0 [got 0, want 1]",
	"applied/series-hard-100-tenths":                               "naive left-to-right summation: the error grows with the number of terms, so 'exact' holds to a few ulps only for short lists [rel error 1.95e-15 vs claim 8.88e-16]",
	"applied/series-hard-1e3-tenths":                               "naive left-to-right summation: the error grows with the number of terms, so 'exact' holds to a few ulps only for short lists [rel error 1.41e-14 vs claim 8.88e-16]",
	"applied/series-hard-1e5-tenths":                               "naive left-to-right summation: the error grows with the number of terms, so 'exact' holds to a few ulps only for short lists [rel error 1.88e-12 vs claim 8.88e-16]",
	"applied/series-hard-1e6-ohm-values":                           "naive left-to-right summation: the error grows with the number of terms, so 'exact' holds to a few ulps only for short lists [rel error 1.03e-11 vs claim 8.88e-16]",
	"applied/snell-cond-near-critical-1e-12":                       "ill-conditioned: asin amplifies the 1.1e-16 rounding of sin(thetaR) by 1/cos(thetaR) near the critical angle [rel error 5.74e-11 vs claim 1e-14]",
	"applied/snell-cond-near-critical-1e-14":                       "ill-conditioned: asin amplifies the 1.1e-16 rounding of sin(thetaR) by 1/cos(thetaR) near the critical angle [rel error 3.56e-10 vs claim 1e-14]",
	"applied/snell-cond-near-critical-1e-9":                        "ill-conditioned: asin amplifies the 1.1e-16 rounding of sin(thetaR) by 1/cos(thetaR) near the critical angle [rel error 9.5e-13 vs claim 1e-14]",
	"applied/soundintensity-extreme-r2-overflow":                   "4*pi*r*r overflows to +Inf, so the intensity comes out 0 [got 0, want 7.958e-22]",
	"applied/spring-hard-spring-balances-damper-1":                 "-k*x and c*v nearly cancel, and each rounded product misses the exact one by more than their difference [got 0, want 1.332e-17]",
	"applied/spring-hard-spring-balances-damper-2":                 "-k*x and c*v nearly cancel, and each rounded product misses the exact one by more than their difference [got 0, want -3.469e-16]",
	"applied/spring-hard-spring-balances-damper-3":                 "-k*x and c*v nearly cancel, and each rounded product misses the exact one by more than their difference [rel error 0.21 vs claim 3.33e-16]",
	"applied/tonemap-r-extreme-v-squared-overflow":                 "v*(1+v/wp^2) overflows to +Inf [got inf, want 1e+155]",
	"applied/tresca-extreme-difference-overflow":                   "max-min overflows to +Inf before the halving [got inf, want 1.5e+308]",
	"applied/vonmises-extreme-squares-overflow":                    "the squared differences overflow to +Inf (the documented range is 'any real numbers') [got inf, want 1e+160]",
	"applied/vonmises-extreme-squares-underflow":                   "the squared differences underflow to 0 (the documented range is 'any real numbers') [got 0, want 1e-170]",
	"applied/xyz2lab-L-hard-dark-linear-branch-1e-6":               "116*f(t) - 16 cancels for dark colours (t = Y/Yn small, linear branch) [rel error 1.27e-12 vs claim 1e-14]",
	"applied/xyz2lab-L-hard-dark-linear-branch-1e-9":               "116*f(t) - 16 cancels for dark colours (t = Y/Yn small, linear branch) [rel error 4.59e-10 vs claim 1e-14]",
	"applied/xyz2lab-a-hard-dark-linear-branch-1e-6":               "f(X/Xn) - f(Y/Yn) cancels for dark colours (linear branch); the absolute error is about 1e-14 [rel error 4.52e-12 vs claim 1e-14]",
	"applied/xyz2lab-a-hard-dark-linear-branch-1e-9":               "f(X/Xn) - f(Y/Yn) cancels for dark colours (linear branch); the absolute error is about 1e-14 [rel error 2.34e-10 vs claim 1e-14]",
	"applied/xyz2lab-a-hard-near-neutral-1e-12":                    "f(X/Xn) - f(Y/Yn) cancels near a neutral colour; the absolute error is about 1e-14 [rel error 0.000309 vs claim 1e-14]",
	"applied/xyz2lab-a-hard-near-neutral-1e-9":                     "f(X/Xn) - f(Y/Yn) cancels near a neutral colour; the absolute error is about 1e-14 [rel error 2.72e-07 vs claim 1e-14]",
	"applied/xyz2lab-b-hard-dark-linear-branch-1e-6":               "f(X/Xn) - f(Y/Yn) cancels for dark colours (linear branch); the absolute error is about 1e-14 [rel error 5.13e-12 vs claim 1e-14]",
	"applied/xyz2lab-b-hard-dark-linear-branch-1e-9":               "f(X/Xn) - f(Y/Yn) cancels for dark colours (linear branch); the absolute error is about 1e-14 [rel error 1.99e-09 vs claim 1e-14]",
	"applied/xyz2lab-b-hard-near-neutral-1e-12":                    "f(X/Xn) - f(Y/Yn) cancels near a neutral colour; the absolute error is about 1e-14 [rel error 7.31e-05 vs claim 1e-14]",
	"applied/xyz2rgb-b-hard-dark":                                  "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 5.52e-10 vs claim 1e-14]",
	"applied/xyz2rgb-b-hard-out-of-gamut":                          "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 2.2e-07 vs claim 1e-14]",
	"applied/xyz2rgb-b-typ-d65-white":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 2.35e-08 vs claim 1e-14]",
	"applied/xyz2rgb-b-typ-mid-gray":                               "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 2.35e-08 vs claim 1e-14]",
	"applied/xyz2rgb-b-typ-saturated":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 7.04e-09 vs claim 1e-14]",
	"applied/xyz2rgb-g-hard-dark":                                  "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 3.95e-08 vs claim 1e-14]",
	"applied/xyz2rgb-g-hard-out-of-gamut":                          "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 5.54e-07 vs claim 1e-14]",
	"applied/xyz2rgb-g-typ-d65-white":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 1.52e-07 vs claim 1e-14]",
	"applied/xyz2rgb-g-typ-mid-gray":                               "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 1.52e-07 vs claim 1e-14]",
	"applied/xyz2rgb-g-typ-saturated":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 1.66e-08 vs claim 1e-14]",
	"applied/xyz2rgb-r-hard-dark":                                  "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 3.8e-07 vs claim 1e-14]",
	"applied/xyz2rgb-r-hard-out-of-gamut":                          "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 1.92e-07 vs claim 1e-14]",
	"applied/xyz2rgb-r-typ-d65-white":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 9.45e-08 vs claim 1e-14]",
	"applied/xyz2rgb-r-typ-mid-gray":                               "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 9.45e-08 vs claim 1e-14]",
	"applied/xyz2rgb-r-typ-saturated":                              "the inverse matrix is a 7-digit table, not the exact inverse of the forward matrix: about 1e-7 [rel error 2.93e-06 vs claim 1e-14]",
}
