package infogeo

import "math"

// A BregmanGen specifies a Bregman divergence via its generator phi (a
// strictly convex differentiable function on the appropriate domain) and
// its derivative gradPhi.  The induced divergence is
//
//	D_phi(x, y) = phi(x) - phi(y) - <grad phi(y), x - y>
//
// element-wise summed when applied to vectors.  D_phi is non-negative,
// zero iff x = y, and is convex in x but generally not symmetric.
type BregmanGen struct {
	// Phi evaluates phi(x) summed elementwise.
	Phi func(x []float64) float64
	// GradPhi writes (d phi / d x)(x) into out.  out and x may alias.
	GradPhi func(x []float64, out []float64)
}

// Bregman computes D_phi(x, y) given a generator.  No validation of the
// domain is performed; callers must ensure x and y lie in the domain of
// phi (e.g., positive scalars for Itakura-Saito, the simplex for KL).
//
// Reference: Banerjee A., Merugu S., Dhillon I. S. & Ghosh J. (2005).
// Clustering with Bregman divergences.  JMLR 6:1705-1749.
func Bregman(gen BregmanGen, x, y []float64) (float64, error) {
	if len(x) != len(y) {
		return 0, ErrLengthMismatch
	}
	if len(x) == 0 {
		return 0, nil
	}
	if gen.Phi == nil || gen.GradPhi == nil {
		return 0, ErrInvalidParameter
	}
	gradY := make([]float64, len(y))
	gen.GradPhi(y, gradY)
	phiX := gen.Phi(x)
	phiY := gen.Phi(y)
	var dot float64
	for i, gi := range gradY {
		dot += gi * (x[i] - y[i])
	}
	return phiX - phiY - dot, nil
}

// =========================================================================
// Named Bregman divergences
// =========================================================================

// SquaredEuclidean returns 0.5 * ||x - y||^2, the Bregman divergence
// generated by phi(x) = 0.5 * ||x||^2.  Symmetric (rare for a Bregman
// divergence — squared Euclidean is the unique symmetric Bregman).  Defined
// for any x, y in R^n.
func SquaredEuclidean(x, y []float64) (float64, error) {
	if len(x) != len(y) {
		return 0, ErrLengthMismatch
	}
	var sum float64
	for i, xi := range x {
		d := xi - y[i]
		sum += d * d
	}
	return 0.5 * sum, nil
}

// GeneralisedKL returns the generalised Kullback-Leibler divergence over
// non-negative measures (does not require sum to 1):
//
//	D(x, y) = sum_i ( x_i * log(x_i / y_i) - x_i + y_i )
//
// Generated by phi(x) = sum_i x_i * (log x_i - 1).  Reduces to standard KL
// when x and y are probability vectors (sum cancels).  Valid for x_i, y_i
// >= 0.  Convention: 0 log 0 = 0; +Inf if x_i > 0 and y_i = 0.
func GeneralisedKL(x, y []float64) (float64, error) {
	if len(x) != len(y) {
		return 0, ErrLengthMismatch
	}
	var sum float64
	for i, xi := range x {
		yi := y[i]
		if xi < 0 || yi < 0 {
			return 0, ErrInvalidParameter
		}
		switch {
		case xi == 0:
			sum += yi
		case yi == 0:
			return math.Inf(1), nil
		default:
			sum += xi*math.Log(xi/yi) - xi + yi
		}
	}
	return sum, nil
}

// ItakuraSaito returns the Itakura-Saito divergence over positive scalars
// (per element):
//
//	D(x, y) = sum_i ( x_i / y_i - log(x_i / y_i) - 1 )
//
// Generated by phi(x) = -sum_i log(x_i).  Standard for power-spectral
// audio comparisons; scale-invariant.  Requires x_i > 0 and y_i > 0;
// returns ErrInvalidParameter otherwise.
//
// Reference: Itakura F. & Saito S. (1968). Analysis synthesis telephony
// based on the maximum likelihood method.  Proc. 6th Int. Cong. on
// Acoustics.
func ItakuraSaito(x, y []float64) (float64, error) {
	if len(x) != len(y) {
		return 0, ErrLengthMismatch
	}
	var sum float64
	for i, xi := range x {
		yi := y[i]
		if !(xi > 0) || !(yi > 0) {
			return 0, ErrInvalidParameter
		}
		ratio := xi / yi
		sum += ratio - math.Log(ratio) - 1.0
	}
	return sum, nil
}

// MahalanobisSquared returns the squared Mahalanobis distance
//
//	D(x, y) = (x - y)^T M (x - y)
//
// where M is a positive-definite n-by-n matrix in row-major form.  This is
// the Bregman divergence generated by phi(x) = 0.5 x^T M x.  Caller must
// ensure M is symmetric positive-definite; no check is performed.  M must
// have len n*n.
func MahalanobisSquared(x, y, M []float64) (float64, error) {
	if len(x) != len(y) {
		return 0, ErrLengthMismatch
	}
	n := len(x)
	if len(M) != n*n {
		return 0, ErrInvalidParameter
	}
	// d = x - y
	d := make([]float64, n)
	for i, xi := range x {
		d[i] = xi - y[i]
	}
	// q = d^T M d
	var q float64
	for i := 0; i < n; i++ {
		var row float64
		for j := 0; j < n; j++ {
			row += M[i*n+j] * d[j]
		}
		q += d[i] * row
	}
	return q, nil
}
