package agreement

import "math"

// MaxExactPermN is the largest number of paired observations for which
// PairedPermutationTest enumerates the full 2^n sign-flip null distribution.
// At n = 20 that is 2^20 ~ 1.05 million sign vectors, which is fast and
// exhaustive. The exact permutation test matters precisely in this small-n
// regime, where the asymptotic normal / t approximations are unreliable; at
// larger n those approximations are accurate, and an EXACT permutation p
// there would require Monte-Carlo sampling, which needs a random number
// generator this deterministic, seed-free implementation deliberately
// excludes. PairedPermutationTest therefore returns ErrSampleTooLargeForExact
// rather than silently approximating, so no caller mistakes an approximation
// for an exact value.
const MaxExactPermN = 20

// PairedPermutationTest performs the EXACT two-sided paired permutation
// (randomization) test on two positionally-paired numeric samples x and y —
// the assumption-free counterpart to the paired t-test. It is deterministic:
// it enumerates the entire null distribution and uses no random number
// generator or seed.
//
// # Method
//
// Form the paired differences d_i = x_i - y_i and the observed test statistic
//
//	S_obs = sum_i d_i.
//
// Under the null hypothesis that each difference is symmetrically distributed
// about zero, the sign of every d_i is exchangeable, so the null distribution
// of the statistic is generated by every assignment of signs eps_i in {-1,+1}:
//
//	S(eps) = sum_i eps_i * d_i.
//
// There are 2^n such sign vectors. The exact two-sided p-value is the exact
// fraction of them whose statistic is at least as extreme (in absolute value)
// as the observed one:
//
//	p = #{ eps : |S(eps)| >= |S_obs| } / 2^n.
//
// The observed sign vector eps = (+1,...,+1) is itself one of the enumerated
// arrangements and always satisfies the inequality, so the numerator is always
// >= 1 and no ad-hoc "add one" correction is applied (that correction, Phipson
// & Smyth 2010, is only needed when the null is RANDOMLY sampled rather than
// exhaustively enumerated). The enumeration is exact and complete, so the
// returned p-value is the exact permutation p-value, not an estimate.
//
// A difference of exactly 0 is invariant under sign flips and so does not
// change S(eps); such pairs leave the p-value unchanged but still consume one
// of the n enumerated bits.
//
// # Returns
//
// The observed statistic S_obs and the exact two-sided p-value. Errors:
// ErrLengthMismatch if x and y differ in length, ErrEmptyInput if they are
// empty, and ErrSampleTooLargeForExact if n > MaxExactPermN. If any difference
// is non-finite (NaN or +/-Inf) the statistic and p-value are both NaN.
//
// # Golden vectors
//
//   - Hand-enumerable case, differences (1, 2, 3), S_obs = 6: of the 8 sign
//     vectors only (+,+,+) -> +6 and (-,-,-) -> -6 reach |S| >= 6, so
//     p = 2/8 = 0.25.
//   - Darwin's Zea mays data (Fisher 1935, The Design of Experiments, §21),
//     the 15 cross- minus self-fertilised plant-height differences in eighths
//     of an inch: S_obs = 314. Fisher's randomization test finds 863 of the
//     2^15 = 32768 arrangements with S >= 314 (also in Ernst 2004); by
//     symmetry 863 have S <= -314, so the exact two-sided p-value is
//     1726/32768 = 0.052673828125.
//
// References:
//   - Fisher, R.A. (1935). The Design of Experiments. Oliver & Boyd. §21
//     (Darwin's Zea mays data).
//   - Ernst, M.D. (2004). Permutation methods: a basis for exact inference.
//     Statistical Science 19(4): 676-685.
//   - Phipson, B., Smyth, G.K. (2010). Permutation p-values should never be
//     zero. Statistical Applications in Genetics and Molecular Biology 9(1).
func PairedPermutationTest(x, y []float64) (statistic, pValue float64, err error) {
	if len(x) != len(y) {
		return 0, 0, ErrLengthMismatch
	}
	n := len(x)
	if n == 0 {
		return 0, 0, ErrEmptyInput
	}
	if n > MaxExactPermN {
		return 0, 0, ErrSampleTooLargeForExact
	}

	diff := make([]float64, n)
	var sObs float64
	for i := range x {
		d := x[i] - y[i]
		if math.IsNaN(d) || math.IsInf(d, 0) {
			return math.NaN(), math.NaN(), nil
		}
		diff[i] = d
		sObs += d
	}
	absObs := math.Abs(sObs)

	// Enumerate all 2^n sign vectors. Bit j of the mask selects the sign of
	// diff[j]: 1 => +diff[j], 0 => -diff[j].
	total := uint64(1) << uint(n)
	var extreme uint64
	for mask := uint64(0); mask < total; mask++ {
		var s float64
		for j := 0; j < n; j++ {
			if mask&(uint64(1)<<uint(j)) != 0 {
				s += diff[j]
			} else {
				s -= diff[j]
			}
		}
		if math.Abs(s) >= absObs {
			extreme++
		}
	}
	return sObs, float64(extreme) / float64(total), nil
}
